// frontend/app/dashboard/receitas/page.tsx
'use client';

import React, { useState, useEffect, useMemo } from 'react';
import { useSession } from 'next-auth/react';
import { useRouter } from 'next/navigation';
import { 
  Loader2, 
  ArrowUpRight, 
  ArrowDownLeft, 
  TrendingUp, 
  Wallet,
  CreditCard,
  Trash2,
  AlertTriangle
} from 'lucide-react';
import { Header } from '@/components/header';
import { toast } from 'sonner';
import { GlowCard, GlowButton, GlowBadge } from '@/components/custom/GlowUI';
import { GlowDialog } from '@/components/custom/GlowDialog';
import { GlowUpload } from '@/components/custom/GlowUpload';
import { 
  GlowTable, 
  GlowTableHeader, 
  GlowTableBody, 
  GlowTableRow, 
  GlowTableHead, 
  GlowTableCell, 
  GlowTableContainer 
} from '@/components/custom/GlowTable';
import { 
  getTransactions, 
  parseStatement, 
  confirmTransactions, 
  deleteTransaction,
  updateTransactionClassification,
  TransactionPayload 
} from '@/services/transaction.service';
import { cn } from '@/lib/utils';

export default function ReceitasPage() {
  const router = useRouter();
  const { data: session, status } = useSession();

  // Abas e Filtros principais
  const [activeTab, setActiveTab] = useState<'business_pj' | 'personal_pf' | 'transfer' | 'pending'>('business_pj');
  const [activeSource, setActiveSource] = useState<'checking_account' | 'credit_card'>('checking_account');

  // Estados dos dados
  const [history, setHistory] = useState<TransactionPayload[]>([]);
  const [tempTransactions, setTempTransactions] = useState<TransactionPayload[]>([]);
  
  // Estados da interface de importação
  const [isImportModalOpen, setIsImportModalOpen] = useState(false);
  const [file, setFile] = useState<File | null>(null);
  
  // Loadings e Estados do Dialog de Exclusão
  const [fetchLoading, setFetchLoading] = useState(false);
  const [importLoading, setImportLoading] = useState(false);
  const [confirmLoading, setConfirmLoading] = useState(false);
  const [isDeleteDialogOpen, setIsDeleteDialogOpen] = useState(false);
  const [transactionToDelete, setTransactionToDelete] = useState<number | null>(null);

  // Proteger rota no frontend
  useEffect(() => {
    if (status === 'unauthenticated') {
      router.push('/login');
    }
  }, [status, router]);

  // Carrega histórico do banco
  const fetchHistory = async () => {
    if (!session?.accessToken) return;
    setFetchLoading(true);
    try {
      const response = await getTransactions(session.accessToken);
      if (response.success) {
        setHistory(response.data || []);
      } else {
        console.error('Falha ao buscar transações:', response.message);
      }
    } catch (err) {
      console.error('Erro ao buscar histórico:', err);
    } finally {
      setFetchLoading(false);
    }
  };

  useEffect(() => {
    if (status === 'authenticated') {
      fetchHistory();
    }
  }, [status, session]);

  // Filtra o histórico com base nas abas selecionadas
  const filteredHistory = useMemo(() => {
    return history.filter(
      (tx) => tx.source === activeSource && tx.classification === activeTab
    );
  }, [history, activeTab, activeSource]);

  // Cálculo dinâmico dos KPIs da aba e origem ativas (baseado no histórico persistido do banco)
  const kpis = useMemo(() => {
    let faturamento = 0; // Entradas
    let gastos = 0;      // Saídas

    filteredHistory.forEach((tx) => {
      if (tx.amount > 0) {
        faturamento += tx.amount;
      } else {
        gastos += Math.abs(tx.amount);
      }
    });

    return {
      faturamento,
      gastos,
      lucro: faturamento - gastos,
    };
  }, [filteredHistory]);

  const kpiConfig = useMemo(() => {
    let labelFat = 'Faturamento (PJ)';
    let labelGas = 'Gastos (PJ)';
    let labelLuc = 'Lucro Líquido';

    if (activeTab === 'personal_pf') {
      labelFat = 'Entradas (PF)';
      labelGas = 'Saídas (PF)';
      labelLuc = 'Saldo (PF)';
    } else if (activeTab === 'transfer') {
      labelFat = 'Entradas (Neutro)';
      labelGas = 'Saídas (Neutro)';
      labelLuc = 'Saldo (Neutro)';
    } else if (activeTab === 'pending') {
      labelFat = 'Entradas (Pendentes)';
      labelGas = 'Saídas (Pendentes)';
      labelLuc = 'Saldo (Pendente)';
    }

    return [
      {
        label: labelFat,
        value: kpis.faturamento,
        icon: ArrowUpRight,
        iconColor: 'text-emerald-500',
      },
      {
        label: labelGas,
        value: kpis.gastos,
        icon: ArrowDownLeft,
        iconColor: 'text-rose-500',
      },
      {
        label: labelLuc,
        value: kpis.lucro,
        icon: TrendingUp,
        iconColor: kpis.lucro >= 0 ? 'text-emerald-500' : 'text-rose-500',
        valueClass: kpis.lucro >= 0 ? 'text-emerald-500 dark:text-emerald-400' : 'text-rose-500 dark:text-rose-400',
      },
    ];
  }, [kpis, activeTab]);

  const handleFileSelect = (selectedFile: File) => {
    setFile(selectedFile);
  };

  // Envia arquivo OFX para o backend estruturar temporariamente na tela
  const handleUploadOFX = async () => {
    if (!file || !session?.accessToken) return;

    const toastId = toast.loading('Processando arquivo OFX...');
    setImportLoading(true);
    setTempTransactions([]);

    try {
      const response = await parseStatement({
        source: activeSource,
        file,
        accessToken: session.accessToken,
      });

      if (!response.success) {
        throw new Error(response.message || 'Erro ao processar o arquivo OFX.');
      }

      setTempTransactions(response.data || []);
      toast.success('Extrato processado com sucesso! Classifique os lançamentos.', { id: toastId });
    } catch (err: any) {
      toast.error(err.message || 'Falha ao importar o arquivo.', { id: toastId });
    } finally {
      setImportLoading(false);
    }
  };

  // Classifica transação temporária em memória
  const handleClassifyTemp = (index: number, classification: 'business_pj' | 'personal_pf' | 'transfer') => {
    setTempTransactions((prev) =>
      prev.map((tx, idx) => (idx === index ? { ...tx, classification } : tx))
    );
  };

  // Salva transações classificadas no banco de dados e recarrega a página
  const handleConfirmImport = async () => {
    if (!session?.accessToken) return;

    const toastId = toast.loading('Salvando lançamentos no banco...');
    setConfirmLoading(true);

    try {
      const response = await confirmTransactions(tempTransactions, session.accessToken);
      if (!response.success) {
        throw new Error(response.message || 'Erro ao salvar lançamentos.');
      }

      toast.success('Transações salvas e conciliação realizada com sucesso!', { id: toastId });
      setTempTransactions([]);
      setFile(null);
      setIsImportModalOpen(false);
      
      // Recarrega histórico para atualizar os KPIs e tabela principal
      await fetchHistory();
    } catch (err: any) {
      toast.error(err.message || 'Falha ao confirmar fechamento.', { id: toastId });
    } finally {
      setConfirmLoading(false);
    }
  };

  // Exclui uma transação salva permanentemente
  const handleDeleteSaved = async (id: number) => {
    if (!session?.accessToken) return;
    
    const toastId = toast.loading('Excluindo transação...');
    try {
      const response = await deleteTransaction(id, session.accessToken);
      if (response.success) {
        setHistory((prev) => prev.filter((tx) => tx.id !== id));
        toast.success('Transação excluída com sucesso!', { id: toastId });
      } else {
        toast.error(response.message || 'Erro ao excluir a transação.', { id: toastId });
      }
    } catch (err) {
      console.error('Erro ao excluir transação:', err);
      toast.error('Erro de conexão ao excluir a transação.', { id: toastId });
    }
  };

  // Altera a classificação de uma transação já persistida no banco
  const handleReclassifySaved = async (id: number, classification: 'business_pj' | 'personal_pf' | 'transfer') => {
    if (!session?.accessToken) return;
    
    const toastId = toast.loading('Atualizando classificação...');
    try {
      const response = await updateTransactionClassification(id, classification, session.accessToken);
      if (response.success) {
        setHistory((prev) =>
          prev.map((tx) => (tx.id === id ? { ...tx, classification } : tx))
        );
        toast.success('Classificação atualizada com sucesso!', { id: toastId });
      } else {
        toast.error(response.message || 'Erro ao alterar a classificação.', { id: toastId });
      }
    } catch (err) {
      console.error('Erro ao alterar classificação:', err);
      toast.error('Erro de conexão ao alterar a classificação.', { id: toastId });
    }
  };

  if (status === 'loading' || status === 'unauthenticated') {
    return (
      <div className="flex-1 flex items-center justify-center min-h-[400px]">
        <div className="flex flex-col items-center gap-2 select-none">
          <Loader2 className="h-8 w-8 animate-spin text-zinc-400" />
          <p className="text-xs text-zinc-400">Carregando Receitas...</p>
        </div>
      </div>
    );
  }

  const mainTabs = [
    { label: 'Pendentes', value: 'pending' },
    { label: 'Pessoa Jurídica (PJ)', value: 'business_pj' },
    { label: 'Pessoa Física (PF)', value: 'personal_pf' },
    { label: 'Neutro / Transferências', value: 'transfer' },
  ] as const;

  const sourceTabs = [
    { label: 'Conta Corrente', value: 'checking_account', icon: Wallet },
    { label: 'Cartão de Crédito', value: 'credit_card', icon: CreditCard },
  ] as const;

  return (
    <div className="flex flex-col flex-1">
      <Header />

      <main className="flex-1 p-6 space-y-6 max-w-6xl w-full mx-auto">
        
        {/* Cabeçalho da Página com Título e Botão de Ação */}
        <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
          <div>
            <h1 className="text-xl font-bold text-gray-950 dark:text-white">Fluxo de Caixa</h1>
            <p className="text-xs text-gray-400 mt-0.5">
              Acompanhe seu faturamento, controle despesas e faça conciliações rápidas via extrato.
            </p>
          </div>
          <GlowButton 
            onClick={() => {
              setTempTransactions([]);
              setFile(null);
              setIsImportModalOpen(true);
            }}
            className="text-xs font-semibold uppercase tracking-wider px-3.5 py-2 rounded-lg"
          >
            Importar Extrato OFX
          </GlowButton>
        </div>

        {/* Abas Principais (Pendentes vs PJ vs PF vs Neutro) */}
        <div className="flex gap-4 border-b border-zinc-150 dark:border-zinc-800/80 overflow-x-auto select-none">
          {mainTabs.map((tab) => (
            <button
              key={tab.value}
              onClick={() => setActiveTab(tab.value)}
              className={cn(
                "pb-2.5 px-1 text-xs font-semibold uppercase tracking-wider border-b-2 transition-all whitespace-nowrap cursor-pointer",
                activeTab === tab.value
                  ? "border-emerald-500 text-emerald-600 dark:text-emerald-400 font-bold"
                  : "border-transparent text-zinc-400 dark:text-zinc-500 hover:text-zinc-900 dark:hover:text-white"
              )}
            >
              {tab.label}
            </button>
          ))}
        </div>

        {/* Abas Secundárias (Conta Corrente vs Cartão) */}
        <div className="flex bg-zinc-100/60 dark:bg-zinc-800/50 p-1 rounded-lg self-start select-none">
          {sourceTabs.map((src) => {
            const Icon = src.icon;
            return (
              <button
                key={src.value}
                onClick={() => setActiveSource(src.value)}
                className={cn(
                  "flex items-center gap-1.5 px-3 py-1.5 rounded-md text-[10px] font-bold uppercase tracking-wider transition-all cursor-pointer",
                  activeSource === src.value
                    ? "bg-white dark:bg-zinc-900 text-zinc-950 dark:text-white shadow-sm"
                    : "text-zinc-400 dark:text-zinc-500 hover:text-zinc-900 dark:hover:text-white"
                )}
              >
                <Icon className="h-3.5 w-3.5 shrink-0" />
                {src.label}
              </button>
            );
          })}
        </div>

        {/* Cards de KPIs (Atualizados com base nas seleções de abas) */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {kpiConfig.map((kpi) => {
            const Icon = kpi.icon;
            return (
              <GlowCard key={kpi.label} className="p-4 flex flex-col gap-1 items-center text-center">
                <div className="flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-wider text-zinc-400 select-none">
                  <Icon className={cn("size-4 shrink-0", kpi.iconColor)} />
                  <span>{kpi.label}</span>
                </div>
                <div className={cn("text-2xl font-semibold tracking-tight mt-1 font-mono", kpi.valueClass || "text-zinc-900 dark:text-white")}>
                  R$ {kpi.value.toLocaleString('pt-BR', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                </div>
              </GlowCard>
            );
          })}
        </div>

        {/* Tabela de Histórico Persistido */}
        <GlowTableContainer>
          <div className="p-5 border-b border-zinc-100 dark:border-zinc-800/80 bg-zinc-50/20 dark:bg-zinc-900/10">
            <h3 className="text-xs font-bold uppercase tracking-wider text-zinc-800 dark:text-white">Lançamentos Conciliados</h3>
            <p className="text-[10px] text-zinc-400 font-mono mt-0.5">Valores persistidos no banco de dados</p>
          </div>

          {fetchLoading ? (
            <div className="p-12 flex justify-center items-center">
              <Loader2 className="h-6 w-6 animate-spin text-zinc-405" />
            </div>
          ) : filteredHistory.length === 0 ? (
            <div className="p-12 text-center text-xs text-zinc-400 select-none">
              Nenhum lançamento registrado para estes filtros.
            </div>
          ) : (
            <GlowTable>
              <GlowTableHeader>
                <GlowTableRow>
                  <GlowTableHead>Data</GlowTableHead>
                  <GlowTableHead>Descrição</GlowTableHead>
                  <GlowTableHead>Valor</GlowTableHead>
                  <GlowTableHead className="text-center">Classificação</GlowTableHead>
                  <GlowTableHead className="text-center"></GlowTableHead>
                </GlowTableRow>
              </GlowTableHeader>
              <GlowTableBody>
                {filteredHistory.map((tx) => {
                  const isPositive = tx.amount > 0;
                  return (
                    <GlowTableRow key={tx.id}>
                      <GlowTableCell className="font-mono text-zinc-450 dark:text-zinc-500 whitespace-nowrap">
                        {tx.transaction_date.split('-').reverse().join('/')}
                      </GlowTableCell>
                      <GlowTableCell className="whitespace-normal break-words max-w-[150px] sm:max-w-xs">
                        <div className="font-medium text-zinc-950 dark:text-white">{tx.description}</div>
                        {tx.fit_id && (
                          <div className="text-[9px] text-zinc-400 dark:text-zinc-500 font-mono mt-0.5">
                            FITID: {tx.fit_id}
                          </div>
                        )}
                      </GlowTableCell>
                      <GlowTableCell className={cn("font-semibold font-mono", isPositive ? "text-emerald-500" : "text-rose-500")}>
                        {isPositive ? '+' : ''}R$ {tx.amount.toLocaleString('pt-BR', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                      </GlowTableCell>
                      <GlowTableCell>
                        <div className="flex justify-center gap-1">
                          <GlowButton
                            variant={tx.classification === 'business_pj' ? 'primary' : 'ghost'}
                            onClick={() => handleReclassifySaved(tx.id!, 'business_pj')}
                            className="h-7 px-2.5 rounded-lg text-[9px]"
                          >
                            PJ
                          </GlowButton>
                          <GlowButton
                            variant={tx.classification === 'personal_pf' ? 'secondary' : 'ghost'}
                            onClick={() => handleReclassifySaved(tx.id!, 'personal_pf')}
                            className="h-7 px-2.5 rounded-lg text-[9px] bg-sky-500/10 hover:bg-sky-500/20 text-sky-500 border-transparent hover:border-transparent dark:bg-sky-500/10"
                          >
                            PF
                          </GlowButton>
                          <GlowButton
                            variant={tx.classification === 'transfer' ? 'secondary' : 'ghost'}
                            onClick={() => handleReclassifySaved(tx.id!, 'transfer')}
                            className="h-7 px-2.5 rounded-lg text-[9px]"
                          >
                            Neutro
                          </GlowButton>
                        </div>
                      </GlowTableCell>
                      <GlowTableCell>
                        <div className="flex justify-center">
                          <GlowButton
                            variant="ghost"
                            onClick={() => {
                              setTransactionToDelete(tx.id!);
                              setIsDeleteDialogOpen(true);
                            }}
                            className="p-1 rounded-lg text-rose-500 hover:bg-rose-50 dark:hover:bg-rose-950/20"
                          >
                            <Trash2 className="size-4" />
                          </GlowButton>
                        </div>
                      </GlowTableCell>
                    </GlowTableRow>
                  );
                })}
              </GlowTableBody>
            </GlowTable>
          )}
        </GlowTableContainer>

        {/* Modal/Dialog de Importação e Conciliação */}
        <GlowDialog
          open={isImportModalOpen}
          onOpenChange={setIsImportModalOpen}
          title="Conciliação de Extrato"
          description={`Origem: ${activeSource === 'checking_account' ? 'CONTA CORRENTE' : 'CARTÃO DE CRÉDITO'}`}
        >
          <div className="space-y-4">
            {tempTransactions.length === 0 ? (
              <div className="space-y-4">
                <GlowUpload
                  onFileSelect={handleFileSelect}
                  selectedFile={file}
                  loading={importLoading}
                />
                <GlowButton
                  onClick={handleUploadOFX}
                  disabled={!file || importLoading}
                  loading={importLoading}
                  className="w-full py-2.5"
                >
                  Processar Extrato
                </GlowButton>
              </div>
            ) : (
              <div className="space-y-4 max-h-[50vh] overflow-y-auto pr-1">
                <GlowTableContainer>
                  <GlowTable>
                    <GlowTableHeader>
                      <GlowTableRow>
                        <GlowTableHead>Data</GlowTableHead>
                        <GlowTableHead>Descrição</GlowTableHead>
                        <GlowTableHead>Valor</GlowTableHead>
                        <GlowTableHead className="text-center">Classificação</GlowTableHead>
                      </GlowTableRow>
                    </GlowTableHeader>
                    <GlowTableBody>
                      {tempTransactions.map((tx, index) => {
                        const isPositive = tx.amount > 0;
                        return (
                          <GlowTableRow 
                            key={index}
                            className={cn(
                              tx.is_duplicate && "bg-amber-500/5 opacity-70",
                              tx.classification === 'business_pj' && "bg-emerald-500/5 border-l-2 border-l-emerald-500",
                              tx.classification === 'personal_pf' && "bg-sky-500/5 border-l-2 border-l-sky-500",
                              tx.classification === 'transfer' && "bg-zinc-500/5 border-l-2 border-l-zinc-500"
                            )}
                          >
                            <GlowTableCell className="font-mono text-zinc-450 dark:text-zinc-500 whitespace-nowrap">
                              {tx.transaction_date.split('-').reverse().join('/')}
                            </GlowTableCell>
                            <GlowTableCell className="whitespace-normal break-words max-w-[150px] sm:max-w-xs">
                              <div className="font-medium flex items-center gap-1.5 flex-wrap text-zinc-950 dark:text-white">
                                <span>{tx.description}</span>
                                {tx.is_duplicate && (
                                  <GlowBadge color="amber">Duplicada</GlowBadge>
                                )}
                              </div>
                            </GlowTableCell>
                            <GlowTableCell className={cn("font-semibold font-mono", isPositive ? "text-emerald-500" : "text-rose-500")}>
                              {isPositive ? '+' : ''}R$ {tx.amount.toLocaleString('pt-BR', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                            </GlowTableCell>
                            <GlowTableCell>
                              <div className="flex justify-center gap-1">
                                <GlowButton
                                  variant={tx.classification === 'business_pj' ? 'primary' : 'ghost'}
                                  onClick={() => handleClassifyTemp(index, 'business_pj')}
                                  className="h-7 px-2 rounded-lg text-[9px]"
                                >
                                  PJ
                                </GlowButton>
                                <GlowButton
                                  variant={tx.classification === 'personal_pf' ? 'secondary' : 'ghost'}
                                  onClick={() => handleClassifyTemp(index, 'personal_pf')}
                                  className="h-7 px-2 rounded-lg text-[9px] bg-sky-500/10 hover:bg-sky-500/20 text-sky-500 border-transparent hover:border-transparent dark:bg-sky-500/10"
                                >
                                  PF
                                </GlowButton>
                                <GlowButton
                                  variant={tx.classification === 'transfer' ? 'secondary' : 'ghost'}
                                  onClick={() => handleClassifyTemp(index, 'transfer')}
                                  className="h-7 px-2 rounded-lg text-[9px]"
                                >
                                  Neutro
                                </GlowButton>
                              </div>
                            </GlowTableCell>
                          </GlowTableRow>
                        );
                      })}
                    </GlowTableBody>
                  </GlowTable>
                </GlowTableContainer>
              </div>
            )}

            {tempTransactions.length > 0 && (
              <div className="flex justify-end gap-3 pt-4 border-t border-zinc-100 dark:border-zinc-800/80">
                <GlowButton variant="ghost" onClick={() => setIsImportModalOpen(false)}>
                  Cancelar
                </GlowButton>
                <GlowButton 
                  variant="primary" 
                  loading={confirmLoading}
                  onClick={handleConfirmImport}
                >
                  Confirmar Fechamento
                </GlowButton>
              </div>
            )}
          </div>
        </GlowDialog>

        {/* Dialog de Confirmação de Exclusão (Dupla Confirmação) */}
        <GlowDialog
          open={isDeleteDialogOpen}
          onOpenChange={setIsDeleteDialogOpen}
          className="max-w-[360px]"
        >
          <div className="text-center select-none p-1">
            <div className="w-11 h-11 rounded-full bg-red-50 dark:bg-red-950/20 text-red-500 flex items-center justify-center mx-auto mb-3">
              <AlertTriangle className="size-6 animate-pulse" />
            </div>
            
            <h4 className="text-sm font-semibold text-zinc-900 dark:text-white">Excluir Lançamento?</h4>
            <p className="text-[11px] text-zinc-400 dark:text-zinc-500 mt-1.5 leading-relaxed">
              Você está prestes a excluir esta transação permanentemente. Esta ação atualizará seus relatórios e removerá os dados do servidor.
            </p>
            
            <div className="mt-5 flex gap-2.5">
              <GlowButton 
                variant="ghost" 
                onClick={() => setIsDeleteDialogOpen(false)}
                className="flex-1 py-2" 
              >
                Cancelar
              </GlowButton>
              <GlowButton 
                variant="danger" 
                onClick={() => {
                  if (transactionToDelete !== null) {
                    handleDeleteSaved(transactionToDelete);
                    setIsDeleteDialogOpen(false);
                    setTransactionToDelete(null);
                  }
                }}
                className="flex-1 py-2" 
              >
                Confirmar
              </GlowButton>
            </div>
          </div>
        </GlowDialog>

      </main>
    </div>
  );
}

// frontend-nuxt/pages/dashboard/receitas/index.vue
<template>
  <main class="flex-1 p-6 space-y-6 max-w-6xl w-full mx-auto">
    <!-- Cabeçalho da Página com Título e Botão de Ação -->
    <div class="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
      <div>
        <h1 class="text-2xl font-semibold tracking-tight text-gray-950 dark:text-white">Receitas e Fluxo de Caixa</h1>
        <p class="text-sm text-gray-500 mt-1">
          Acompanhe seu faturamento, controle despesas e faça conciliações rápidas via extrato.
        </p>
      </div>
      <UButton 
        icon="i-heroicons-cloud-arrow-up"
        class="flex items-center gap-2 font-medium"
        @click="openImportModal"
      >
        Importar Extrato OFX
      </UButton>
    </div>

    <!-- Abas Principais (Pendentes vs PJ vs PF vs Neutro) -->
    <div class="border-b border-gray-200 dark:border-zinc-800 flex gap-4 overflow-x-auto">
      <button
        v-for="tab in mainTabs"
        :key="tab.value"
        @click="activeTab = tab.value"
        class="pb-3 px-1 text-sm font-medium border-b-2 transition-colors whitespace-nowrap"
        :class="[
          activeTab === tab.value
            ? 'border-emerald-500 text-emerald-600 dark:text-emerald-400'
            : 'border-transparent text-gray-500 dark:text-zinc-400 hover:text-gray-700 hover:border-gray-300'
        ]"
      >
        {{ tab.label }}
      </button>
    </div>

    <!-- Abas Secundárias (Conta Corrente vs Cartão) -->
    <div class="flex bg-gray-100 dark:bg-zinc-800 p-1 rounded-lg self-start">
      <button
        v-for="src in sourceTabs"
        :key="src.value"
        @click="activeSource = src.value"
        class="flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-medium transition-colors"
        :class="[
          activeSource === src.value
            ? 'bg-white dark:bg-zinc-900 text-gray-950 dark:text-white shadow-sm'
            : 'text-gray-500 dark:text-zinc-400 hover:text-gray-900 dark:hover:text-white'
        ]"
      >
        <UIcon :name="src.icon" class="h-3.5 w-3.5" />
        {{ src.label }}
      </button>
    </div>

    <!-- Cards de KPIs (Atualizados com base nas seleções de abas) -->
    <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
      <UCard :ui="{ body: { padding: 'p-4 pb-3 flex flex-col gap-1 items-center text-center' } }">
        <div class="flex items-center gap-1.5 text-xs font-semibold text-gray-500">
          <UIcon name="i-heroicons-arrow-up-right" class="w-3.5 h-3.5 text-emerald-500 shrink-0" />
          <span>{{ faturamentoLabel }}</span>
        </div>
        <div class="text-2xl font-black tracking-tight text-gray-950 dark:text-white mt-1 font-mono">
          R$ {{ formatCurrency(kpis.faturamento) }}
        </div>
      </UCard>

      <UCard :ui="{ body: { padding: 'p-4 pb-3 flex flex-col gap-1 items-center text-center' } }">
        <div class="flex items-center gap-1.5 text-xs font-semibold text-gray-500">
          <UIcon name="i-heroicons-arrow-down-left" class="w-3.5 h-3.5 text-rose-500 shrink-0" />
          <span>{{ gastosLabel }}</span>
        </div>
        <div class="text-2xl font-black tracking-tight text-gray-950 dark:text-white mt-1 font-mono">
          R$ {{ formatCurrency(kpis.gastos) }}
        </div>
      </UCard>

      <UCard :ui="{ body: { padding: 'p-4 pb-3 flex flex-col gap-1 items-center text-center' } }">
        <div class="flex items-center gap-1.5 text-xs font-semibold text-gray-500">
          <UIcon name="i-heroicons-chart-bar" class="w-3.5 h-3.5 shrink-0" :class="[kpis.lucro >= 0 ? 'text-emerald-500' : 'text-rose-500']" />
          <span>{{ lucroLabel }}</span>
        </div>
        <div class="text-2xl font-black tracking-tight mt-1 font-mono" :class="[kpis.lucro >= 0 ? 'text-emerald-500' : 'text-rose-500']">
          R$ {{ formatCurrency(kpis.lucro) }}
        </div>
      </UCard>
    </div>

    <!-- Tabela de Histórico Persistido -->
    <div class="rounded-xl border border-gray-200 dark:border-zinc-800 bg-white dark:bg-zinc-950 shadow-sm overflow-hidden">
      <div class="p-6 border-b border-gray-200 dark:border-zinc-800 bg-gray-50/50 dark:bg-zinc-900/50">
        <h3 class="text-base font-semibold text-gray-950 dark:text-white">Histórico de Lançamentos</h3>
        <p class="text-xs text-gray-500 mt-1">
          Transações já conciliadas e gravadas no banco de dados para a origem selecionada.
        </p>
      </div>

      <div v-if="fetchLoading" class="p-12 flex justify-center items-center">
        <UIcon name="i-heroicons-arrow-path" class="h-6 w-6 animate-spin text-gray-500" />
      </div>

      <div v-else-if="filteredHistory.length === 0" class="p-12 text-center text-sm text-gray-500">
        Nenhuma transação encontrada no banco de dados para os filtros selecionados.
      </div>

      <div v-else class="overflow-x-auto w-full">
        <table class="w-full text-sm text-left">
          <thead class="bg-gray-50 dark:bg-zinc-900 text-xs font-semibold uppercase text-gray-500 dark:text-zinc-400 border-b border-gray-200 dark:border-zinc-800">
            <tr>
              <th class="px-4 py-3">Data</th>
              <th class="px-4 py-3">Descrição</th>
              <th class="px-4 py-3">Valor</th>
              <th class="px-4 py-3 text-center">Classificação</th>
              <th class="px-4 py-3 text-center">Ações</th>
            </tr>
          </thead>
          <tbody class="divide-y divide-gray-200 dark:divide-zinc-800">
            <tr 
              v-for="tx in filteredHistory" 
              :key="tx.id" 
              class="hover:bg-gray-50 dark:hover:bg-zinc-800/20 transition-colors"
            >
              <td class="px-4 py-3 font-mono text-gray-500 dark:text-zinc-400 whitespace-nowrap">
                {{ formatDate(tx.transaction_date) }}
              </td>
              <td class="px-4 py-3 whitespace-normal break-words max-w-[150px] sm:max-w-xs">
                <div class="font-medium text-gray-950 dark:text-white">{{ tx.description }}</div>
                <div v-if="tx.fit_id" class="text-[10px] text-gray-400 dark:text-zinc-500 font-mono mt-0.5">
                  FITID: {{ tx.fit_id }}
                </div>
              </td>
              <td class="px-4 py-3 font-semibold font-mono whitespace-nowrap" :class="[tx.amount > 0 ? 'text-emerald-500' : 'text-rose-500']">
                R$ {{ formatCurrency(tx.amount) }}
              </td>
              <td class="px-4 py-3">
                <div class="flex justify-center gap-1">
                  <UButton
                    size="xs"
                    :variant="tx.classification === 'business_pj' ? 'solid' : 'outline'"
                    color="emerald"
                    @click="handleReclassifySaved(tx.id!, 'business_pj')"
                  >
                    PJ
                  </UButton>
                  <UButton
                    size="xs"
                    :variant="tx.classification === 'personal_pf' ? 'solid' : 'outline'"
                    color="sky"
                    @click="handleReclassifySaved(tx.id!, 'personal_pf')"
                  >
                    PF
                  </UButton>
                  <UButton
                    size="xs"
                    :variant="tx.classification === 'transfer' ? 'solid' : 'outline'"
                    color="gray"
                    @click="handleReclassifySaved(tx.id!, 'transfer')"
                  >
                    Neutro
                  </UButton>
                </div>
              </td>
              <td class="px-4 py-3">
                <div class="flex justify-center">
                  <UButton
                    size="xs"
                    color="red"
                    variant="light"
                    icon="i-heroicons-trash"
                    class="flex items-center gap-1 font-medium"
                    @click="openDeleteDialog(tx.id!)"
                  >
                    Excluir
                  </UButton>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <!-- Modal/Dialog de Importação e Conciliação -->
    <UModal v-model="isImportModalOpen" prevent-close :ui="{ width: 'sm:max-w-2xl md:max-w-3xl lg:max-w-4xl' }">
      <div class="flex flex-col max-h-[90vh] overflow-hidden bg-white dark:bg-zinc-950 border border-gray-200 dark:border-zinc-800 rounded-lg shadow-xl">
        <div class="p-6 pb-4 border-b border-gray-200 dark:border-zinc-800 shrink-0">
          <h3 class="text-lg font-bold text-gray-900 dark:text-white">Conciliação de Extrato OFX</h3>
          <p class="text-xs text-gray-500 mt-1">
            Origem selecionada: <span class="font-semibold">{{ activeSource === 'checking_account' ? 'Conta Corrente' : 'Cartão de Crédito' }}</span>
          </p>
        </div>

        <div class="p-6 overflow-y-auto space-y-4 flex-1">
          <!-- Formulário de Upload -->
          <form v-if="tempTransactions.length === 0" @submit.prevent="handleUploadOFX" class="space-y-4 py-4">
            <div class="border border-dashed border-gray-300 dark:border-zinc-700 rounded-xl p-8 flex flex-col items-center justify-center text-center gap-3 bg-gray-50 dark:bg-zinc-900/50">
              <UIcon name="i-heroicons-cloud-arrow-up" class="h-8 w-8 text-gray-400 animate-pulse" />
              <div>
                <label for="ofxFile" class="cursor-pointer text-sm font-semibold text-emerald-500 hover:underline">
                  Clique para selecionar o arquivo
                </label>
                <p class="text-xs text-gray-500 mt-1">Apenas arquivos no formato .ofx</p>
              </div>
              <input
                id="ofxFile"
                type="file"
                accept=".ofx"
                required
                class="hidden"
                @change="handleFileChange"
              />
              <p v-if="file" class="text-xs font-mono bg-gray-100 dark:bg-zinc-800 border border-gray-200 dark:border-zinc-700 px-2.5 py-1 rounded-md text-gray-700 dark:text-zinc-300 mt-2">
                {{ file.name }}
              </p>
            </div>

            <UButton type="submit" block :loading="importLoading" :disabled="!file">
              Carregar Extrato
            </UButton>
          </form>

          <!-- Lista de lançamentos a classificar -->
          <div v-else class="space-y-4">
            <div class="border border-gray-200 dark:border-zinc-800 rounded-md overflow-hidden bg-white dark:bg-zinc-900">
              <div class="overflow-x-auto">
                <table class="w-full text-sm text-left">
                  <thead class="bg-gray-50 dark:bg-zinc-950 text-xs font-semibold uppercase text-gray-500">
                    <tr>
                      <th class="px-4 py-3">Data</th>
                      <th class="px-4 py-3">Descrição</th>
                      <th class="px-4 py-3">Valor</th>
                      <th class="px-4 py-3 text-center">Classificação</th>
                    </tr>
                  </thead>
                  <tbody class="divide-y divide-gray-200 dark:divide-zinc-800">
                    <tr 
                      v-for="(tx, index) in tempTransactions" 
                      :key="index"
                      :class="[
                        tx.is_duplicate 
                          ? 'bg-amber-500/5 opacity-70' 
                          : tx.classification === 'business_pj'
                          ? 'bg-emerald-500/5 border-l-2 border-l-emerald-500'
                          : tx.classification === 'personal_pf'
                          ? 'bg-sky-500/5 border-l-2 border-l-sky-500'
                          : tx.classification === 'transfer'
                          ? 'bg-zinc-500/5 border-l-2 border-l-zinc-500'
                          : ''
                      ]"
                    >
                      <td class="px-4 py-3 font-mono text-gray-500 dark:text-zinc-400 whitespace-nowrap">
                        {{ formatDate(tx.transaction_date) }}
                      </td>
                      <td class="px-4 py-3 whitespace-normal break-words max-w-[150px] sm:max-w-xs">
                        <div class="font-medium flex items-center gap-1.5 flex-wrap">
                          <span>{{ tx.description }}</span>
                          <span v-if="tx.is_duplicate" class="inline-flex items-center gap-1 px-1.5 py-0.5 rounded text-[10px] font-medium bg-amber-50 dark:bg-amber-950/30 text-amber-600 dark:text-amber-400 border border-amber-200 dark:border-amber-900/50">
                            <UIcon name="i-heroicons-exclamation-triangle" class="h-3 w-3" />
                            Duplicada
                          </span>
                        </div>
                      </td>
                      <td class="px-4 py-3 font-semibold font-mono whitespace-nowrap" :class="[tx.amount > 0 ? 'text-emerald-500' : 'text-rose-500']">
                        R$ {{ formatCurrency(tx.amount) }}
                      </td>
                      <td class="px-4 py-3">
                        <div class="flex justify-center gap-1">
                          <UButton
                            size="xs"
                            :variant="tx.classification === 'business_pj' ? 'solid' : 'outline'"
                            color="emerald"
                            @click="handleClassifyTemp(index, 'business_pj')"
                          >
                            PJ
                          </UButton>
                          <UButton
                            size="xs"
                            :variant="tx.classification === 'personal_pf' ? 'solid' : 'outline'"
                            color="sky"
                            @click="handleClassifyTemp(index, 'personal_pf')"
                          >
                            PF
                          </UButton>
                          <UButton
                            size="xs"
                            :variant="tx.classification === 'transfer' ? 'solid' : 'outline'"
                            color="gray"
                            @click="handleClassifyTemp(index, 'transfer')"
                          >
                            Neutro
                          </UButton>
                        </div>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>

        <div class="p-6 border-t border-gray-200 dark:border-zinc-800 flex justify-end gap-3 bg-gray-50 dark:bg-zinc-900/20 shrink-0">
          <UButton color="gray" variant="ghost" @click="isImportModalOpen = false">
            Cancelar
          </UButton>
          <UButton 
            v-if="tempTransactions.length > 0"
            color="emerald"
            icon="i-heroicons-check-circle"
            :loading="confirmLoading"
            @click="handleConfirmImport"
          >
            Confirmar Fechamento
          </UButton>
        </div>
      </div>
    </UModal>

    <!-- Dialog de Confirmação de Exclusão (Dupla Confirmação) -->
    <UModal v-model="isDeleteDialogOpen" :ui="{ width: 'sm:max-w-[425px]' }">
      <div class="p-6 bg-white dark:bg-zinc-900 rounded-lg shadow-xl border border-gray-200 dark:border-zinc-800">
        <div class="flex items-center gap-2 text-red-600 dark:text-red-500 mb-1">
          <UIcon name="i-heroicons-exclamation-triangle" class="h-5 w-5 animate-bounce" />
          <h3 class="text-lg font-bold">Excluir Lançamento</h3>
        </div>
        
        <div class="pt-2 text-sm text-gray-500 dark:text-zinc-400 text-left">
          Você está prestes a excluir esta transação permanentemente. Esta ação atualizará seus relatórios financeiros.
        </div>
        
        <p class="text-[11px] text-gray-400 dark:text-zinc-500 pt-1.5 font-semibold text-left">
          Esta ação é irreversível e removerá permanentemente os registros do banco de dados.
        </p>
        
        <div class="pt-4 flex justify-end gap-3">
          <UButton 
            color="gray" 
            variant="ghost" 
            @click="isDeleteDialogOpen = false"
          >
            Cancelar
          </UButton>
          <UButton 
            color="red" 
            @click="confirmDelete"
          >
            Confirmar Exclusão
          </UButton>
        </div>
      </div>
    </UModal>
  </main>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'

interface TransactionPayload {
  id?: number
  transaction_date: string
  description: string
  amount: number
  source: 'checking_account' | 'credit_card'
  classification: 'pending' | 'business_pj' | 'personal_pf' | 'transfer'
  fit_id?: string | null
  is_duplicate?: boolean
}

const activeTab = ref<'business_pj' | 'personal_pf' | 'transfer' | 'pending'>('business_pj')
const activeSource = ref<'checking_account' | 'credit_card'>('checking_account')

const history = ref<TransactionPayload[]>([])
const tempTransactions = ref<TransactionPayload[]>([])

const isImportModalOpen = ref(false)
const file = ref<File | null>(null)

const fetchLoading = ref(false)
const importLoading = ref(false)
const confirmLoading = ref(false)

const isDeleteDialogOpen = ref(false)
const transactionToDelete = ref<number | null>(null)

const { apiFetch } = useAuth()
const toast = useToast()

const mainTabs = [
  { label: 'Pendentes', value: 'pending' },
  { label: 'Pessoa Jurídica (PJ)', value: 'business_pj' },
  { label: 'Pessoa Física (PF)', value: 'personal_pf' },
  { label: 'Neutro / Transferências', value: 'transfer' }
]

const sourceTabs = [
  { label: 'Conta Corrente', value: 'checking_account', icon: 'i-heroicons-wallet' },
  { label: 'Cartão de Crédito', value: 'credit_card', icon: 'i-heroicons-credit-card' }
]

// Labels dinâmicos para os cards baseados na aba atual
const faturamentoLabel = computed(() => {
  switch (activeTab.value) {
    case 'business_pj': return 'Faturamento (PJ)'
    case 'personal_pf': return 'Entradas (PF)'
    case 'transfer': return 'Entradas (Neutras)'
    default: return 'Entradas (Pendentes)'
  }
})

const gastosLabel = computed(() => {
  switch (activeTab.value) {
    case 'business_pj': return 'Gastos (PJ)'
    case 'personal_pf': return 'Saídas (PF)'
    case 'transfer': return 'Saídas (Neutras)'
    default: return 'Saídas (Pendentes)'
  }
})

const lucroLabel = computed(() => {
  switch (activeTab.value) {
    case 'business_pj': return 'Lucro Líquido'
    case 'personal_pf': return 'Saldo (PF)'
    case 'transfer': return 'Saldo (Neutro)'
    default: return 'Saldo (Pendente)'
  }
})

// Busca histórico
const fetchHistory = async () => {
  fetchLoading.value = true
  try {
    const response: any = await apiFetch('/transactions', { method: 'GET' })
    if (response && response.success) {
      history.value = response.data || []
    } else {
      toast.add({
        title: 'Erro ao carregar histórico',
        description: response?.message || 'Falha ao buscar dados',
        color: 'red'
      })
    }
  } catch (err: any) {
    toast.add({
      title: 'Erro de conexão',
      description: err.message || 'Falha ao buscar dados no backend',
      color: 'red'
    })
  } finally {
    fetchLoading.value = false
  }
}

// Filtra histórico
const filteredHistory = computed(() => {
  return history.value.filter(
    (tx) => tx.source === activeSource.value && tx.classification === activeTab.value
  )
})

// KPIs baseados nos lançamentos filtrados
const kpis = computed(() => {
  let faturamento = 0
  let gastos = 0

  filteredHistory.value.forEach((tx) => {
    if (tx.amount > 0) {
      faturamento += tx.amount
    } else {
      gastos += Math.abs(tx.amount)
    }
  })

  return {
    faturamento,
    gastos,
    lucro: faturamento - gastos
  }
})

// Abre modal de importação
const openImportModal = () => {
  tempTransactions.value = []
  file.value = null
  isImportModalOpen.value = true
}

// Controla upload
const handleFileChange = (e: Event) => {
  const target = e.target as HTMLInputElement
  if (target.files && target.files.length > 0) {
    file.value = target.files[0]
  }
}

const handleUploadOFX = async () => {
  if (!file.value) return

  importLoading.value = true
  tempTransactions.value = []

  const formData = new FormData()
  formData.append('source', activeSource.value)
  formData.append('file', file.value)

  try {
    const response: any = await apiFetch('/transactions/parse', {
      method: 'POST',
      body: formData
    })

    if (response && response.success) {
      tempTransactions.value = response.data || []
      toast.add({
        title: 'Arquivo processado!',
        description: 'Extrato processado com sucesso. Classifique os lançamentos.',
        color: 'green'
      })
    } else {
      toast.add({
        title: 'Falha no upload',
        description: response?.message || 'Erro ao processar o arquivo.',
        color: 'red'
      })
    }
  } catch (err: any) {
    toast.add({
      title: 'Erro de conexão',
      description: err.message || 'Erro ao processar arquivo.',
      color: 'red'
    })
  } finally {
    importLoading.value = false
  }
}

// Classifica lançamento temporário na memória
const handleClassifyTemp = (index: number, classification: 'business_pj' | 'personal_pf' | 'transfer') => {
  tempTransactions.value = tempTransactions.value.map((tx, idx) => 
    idx === index ? { ...tx, classification } : tx
  )
}

// Confirma importação
const handleConfirmImport = async () => {
  confirmLoading.value = true
  try {
    const response: any = await apiFetch('/transactions/confirm', {
      method: 'POST',
      body: { transactions: tempTransactions.value }
    })

    if (response && response.success) {
      toast.add({
        title: 'Lançamentos salvos!',
        description: 'Transações salvas e conciliação realizada com sucesso.',
        color: 'green'
      })
      tempTransactions.value = []
      file.value = null
      isImportModalOpen.value = false
      await fetchHistory()
    } else {
      toast.add({
        title: 'Erro ao salvar',
        description: response?.message || 'Falha ao salvar lançamentos.',
        color: 'red'
      })
    }
  } catch (err: any) {
    toast.add({
      title: 'Erro de conexão',
      description: err.message || 'Falha ao salvar lançamentos.',
      color: 'red'
    })
  } finally {
    confirmLoading.value = false
  }
}

// Reclassifica lançamento salvo no banco
const handleReclassifySaved = async (id: number, classification: 'business_pj' | 'personal_pf' | 'transfer') => {
  try {
    const response: any = await apiFetch(`/transactions/${id}/classify`, {
      method: 'PATCH',
      body: { classification }
    })

    if (response && response.success) {
      history.value = history.value.map((tx) =>
        tx.id === id ? { ...tx, classification } : tx
      )
      toast.add({
        title: 'Classificação atualizada',
        description: 'Classificação atualizada com sucesso.',
        color: 'green'
      })
    } else {
      toast.add({
        title: 'Erro ao reclassificar',
        description: response?.message || 'Erro ao alterar classificação.',
        color: 'red'
      })
    }
  } catch (err: any) {
    toast.add({
      title: 'Erro de conexão',
      description: err.message || 'Erro ao alterar classificação.',
      color: 'red'
    })
  }
}

// Exclui lançamento com dupla confirmação
const openDeleteDialog = (id: number) => {
  transactionToDelete.value = id
  isDeleteDialogOpen.value = true
}

const confirmDelete = async () => {
  if (transactionToDelete.value === null) return
  const id = transactionToDelete.value
  isDeleteDialogOpen.value = false
  transactionToDelete.value = null

  try {
    const response: any = await apiFetch(`/transactions/${id}`, {
      method: 'DELETE'
    })

    if (response && response.success) {
      history.value = history.value.filter((tx) => tx.id !== id)
      toast.add({
        title: 'Lançamento excluído',
        description: 'Transação excluída com sucesso.',
        color: 'green'
      })
    } else {
      toast.add({
        title: 'Erro ao excluir',
        description: response?.message || 'Erro ao excluir transação.',
        color: 'red'
      })
    }
  } catch (err: any) {
    toast.add({
      title: 'Erro de conexão',
      description: err.message || 'Erro de conexão ao excluir transação.',
      color: 'red'
    })
  }
}

// Formatadores
const formatDate = (dateStr: string) => {
  if (!dateStr) return ''
  return dateStr.split('-').reverse().join('/')
}

const formatCurrency = (val: number) => {
  return val.toLocaleString('pt-BR', { minimumFractionDigits: 2, maximumFractionDigits: 2 })
}

onMounted(() => {
  fetchHistory()
})
</script>
