// frontend/src/app/dashboard/receitas/page.tsx
'use client';

import React, { useState, useEffect, useMemo } from 'react';
import { useSession } from 'next-auth/react';
import { useRouter } from 'next/navigation';
import { 
  Loader2, 
  UploadCloud, 
  ArrowUpRight, 
  ArrowDownLeft, 
  TrendingUp, 
  CheckCircle, 
  AlertTriangle,
  Plus,
  CreditCard,
  Wallet,
  X,
  Trash2
} from 'lucide-react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Header } from '@/components/header';
import { 
  getTransactions, 
  parseStatement, 
  confirmTransactions, 
  deleteTransaction,
  updateTransactionClassification,
  TransactionPayload 
} from '@/services/transaction.service';

export default function ReceitasPage() {
  const router = useRouter();
  const { data: session, status } = useSession();

  // Abas e Filtros principais
  const [activeTab, setActiveTab] = useState<'business_pj' | 'personal_pf' | 'transfer' | 'pending'>('business_pj');
  const [activeSource, setActiveSource] = useState<'checking_account' | 'credit_card'>('checking_account');

  // Estados dos dados
  const [history, setHistory] = useState<TransactionPayload[]>([]);
  const [tempTransactions, setTempTransactions] = useState<TransactionPayload[]>([]);
  
  // Estados da interface de importação
  const [isImportModalOpen, setIsImportModalOpen] = useState(false);
  const [file, setFile] = useState<File | null>(null);
  
  // Loadings e Mensagens
  const [fetchLoading, setFetchLoading] = useState(false);
  const [importLoading, setImportLoading] = useState(false);
  const [confirmLoading, setConfirmLoading] = useState(false);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');

  // Proteger rota no frontend
  useEffect(() => {
    if (status === 'unauthenticated') {
      router.push('/login');
    }
  }, [status, router]);

  // Carrega histórico do banco
  const fetchHistory = async () => {
    if (!session?.accessToken) return;
    setFetchLoading(true);
    try {
      const response = await getTransactions(session.accessToken);
      if (response.success) {
        setHistory(response.data || []);
      } else {
        console.error('Falha ao buscar transações:', response.message);
      }
    } catch (err) {
      console.error('Erro ao buscar histórico:', err);
    } finally {
      setFetchLoading(false);
    }
  };

  useEffect(() => {
    if (status === 'authenticated') {
      fetchHistory();
    }
  }, [status, session]);

  // Filtra o histórico com base nas abas selecionadas
  const filteredHistory = useMemo(() => {
    return history.filter(
      (tx) => tx.source === activeSource && tx.classification === activeTab
    );
  }, [history, activeTab, activeSource]);

  // Cálculo dinâmico dos KPIs da aba e origem ativas (baseado no histórico persistido do banco)
  const kpis = useMemo(() => {
    let faturamento = 0; // Entradas
    let gastos = 0;      // Saídas

    filteredHistory.forEach((tx) => {
      if (tx.amount > 0) {
        faturamento += tx.amount;
      } else {
        gastos += Math.abs(tx.amount);
      }
    });

    return {
      faturamento,
      gastos,
      lucro: faturamento - gastos,
    };
  }, [filteredHistory]);

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files.length > 0) {
      setFile(e.target.files[0]);
    }
  };

  // Envia arquivo OFX para o backend estruturar temporariamente na tela
  const handleUploadOFX = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!file || !session?.accessToken) return;

    setError('');
    setImportLoading(true);
    setTempTransactions([]);

    try {
      const response = await parseStatement({
        source: activeSource,
        file,
        accessToken: session.accessToken,
      });

      if (!response.success) {
        throw new Error(response.message || 'Erro ao processar o arquivo OFX.');
      }

      setTempTransactions(response.data || []);
      setSuccess('Extrato processado com sucesso! Classifique os lançamentos abaixo.');
    } catch (err: any) {
      setError(err.message || 'Falha ao importar o arquivo.');
    } finally {
      setImportLoading(false);
    }
  };

  // Classifica transação temporária em memória
  const handleClassifyTemp = (index: number, classification: 'business_pj' | 'personal_pf' | 'transfer') => {
    setTempTransactions((prev) =>
      prev.map((tx, idx) => (idx === index ? { ...tx, classification } : tx))
    );
  };

  // Salva transações classificadas no banco de dados e recarrega a página
  const handleConfirmImport = async () => {
    if (!session?.accessToken) return;

    setError('');
    setConfirmLoading(true);

    try {
      const response = await confirmTransactions(tempTransactions, session.accessToken);
      if (!response.success) {
        throw new Error(response.message || 'Erro ao salvar lançamentos.');
      }

      setSuccess('Transações salvas e conciliação realizada com sucesso!');
      setTempTransactions([]);
      setFile(null);
      setIsImportModalOpen(false);
      
      // Recarrega histórico para atualizar os KPIs e tabela principal
      await fetchHistory();
    } catch (err: any) {
      setError(err.message || 'Falha ao confirmar fechamento.');
    } finally {
      setConfirmLoading(false);
    }
  };

  // Exclui uma transação salva permanentemente
  const handleDeleteSaved = async (id: number) => {
    if (!session?.accessToken) return;
    if (!window.confirm('Tem certeza de que deseja excluir esta transação permanentemente?')) return;
    
    try {
      const response = await deleteTransaction(id, session.accessToken);
      if (response.success) {
        setHistory((prev) => prev.filter((tx) => tx.id !== id));
      } else {
        alert(response.message || 'Erro ao excluir a transação.');
      }
    } catch (err) {
      console.error('Erro ao excluir transação:', err);
      alert('Erro de conexão ao excluir a transação.');
    }
  };

  // Altera a classificação de uma transação já persistida no banco
  const handleReclassifySaved = async (id: number, classification: 'business_pj' | 'personal_pf' | 'transfer') => {
    if (!session?.accessToken) return;
    
    try {
      const response = await updateTransactionClassification(id, classification, session.accessToken);
      if (response.success) {
        setHistory((prev) =>
          prev.map((tx) => (tx.id === id ? { ...tx, classification } : tx))
        );
      } else {
        alert(response.message || 'Erro ao alterar a classificação.');
      }
    } catch (err) {
      console.error('Erro ao alterar classificação:', err);
      alert('Erro de conexão ao alterar a classificação.');
    }
  };

  if (status === 'loading' || status === 'unauthenticated') {
    return (
      <div className="flex-1 flex items-center justify-center min-h-[400px]">
        <div className="flex flex-col items-center gap-2">
          <Loader2 className="h-8 w-8 animate-spin" />
          <p className="text-sm text-muted-foreground">Carregando Receitas...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="flex flex-col flex-1">
      <Header />

      <main className="flex-1 p-6 space-y-6 max-w-6xl w-full mx-auto">
        
        {/* Cabeçalho da Página com Título e Botão de Ação */}
        <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
          <div>
            <h1 className="text-2xl font-bold tracking-tight">Receitas e Fluxo de Caixa</h1>
            <p className="text-sm text-muted-foreground">
              Acompanhe seu faturamento, controle despesas e faça conciliações rápidas via extrato.
            </p>
          </div>
          <Button 
            onClick={() => {
              setError('');
              setSuccess('');
              setTempTransactions([]);
              setFile(null);
              setIsImportModalOpen(true);
            }}
            className="bg-emerald-600 hover:bg-emerald-700 text-white flex items-center gap-2"
          >
            <UploadCloud className="h-4 w-4" />
            Importar Extrato OFX
          </Button>
        </div>

        {/* Abas Principais (Pendentes vs PJ vs PF vs Neutro) */}
        <div className="flex border-b border-muted">
          <button
            onClick={() => setActiveTab('pending')}
            className={`px-4 py-2 text-sm font-medium border-b-2 transition-colors -mb-[2px] ${
              activeTab === 'pending'
                ? 'border-yellow-500 text-yellow-500 font-bold'
                : 'border-transparent text-muted-foreground hover:text-foreground'
            }`}
          >
            Pendentes
          </button>
          <button
            onClick={() => setActiveTab('business_pj')}
            className={`px-4 py-2 text-sm font-medium border-b-2 transition-colors -mb-[2px] ${
              activeTab === 'business_pj'
                ? 'border-emerald-500 text-emerald-500 font-bold'
                : 'border-transparent text-muted-foreground hover:text-foreground'
            }`}
          >
            Pessoa Jurídica (PJ)
          </button>
          <button
            onClick={() => setActiveTab('personal_pf')}
            className={`px-4 py-2 text-sm font-medium border-b-2 transition-colors -mb-[2px] ${
              activeTab === 'personal_pf'
                ? 'border-sky-500 text-sky-500 font-bold'
                : 'border-transparent text-muted-foreground hover:text-foreground'
            }`}
          >
            Pessoa Física (PF)
          </button>
          <button
            onClick={() => setActiveTab('transfer')}
            className={`px-4 py-2 text-sm font-medium border-b-2 transition-colors -mb-[2px] ${
              activeTab === 'transfer'
                ? 'border-zinc-500 text-zinc-500 font-bold'
                : 'border-transparent text-muted-foreground hover:text-foreground'
            }`}
          >
            Neutro / Transferências
          </button>
        </div>

        {/* Abas Secundárias (Conta Corrente vs Cartão) */}
        <div className="flex gap-2">
          <Button
            size="sm"
            variant={activeSource === 'checking_account' ? 'default' : 'outline'}
            onClick={() => setActiveSource('checking_account')}
            className="flex items-center gap-1.5"
          >
            <Wallet className="h-3.5 w-3.5" />
            Conta Corrente
          </Button>
          <Button
            size="sm"
            variant={activeSource === 'credit_card' ? 'default' : 'outline'}
            onClick={() => setActiveSource('credit_card')}
            className="flex items-center gap-1.5"
          >
            <CreditCard className="h-3.5 w-3.5" />
            Cartão de Crédito
          </Button>
        </div>

        {/* Cards de KPIs (Atualizados com base nas seleções de abas) */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <Card className="border-l-4 border-l-green-500">
            <CardHeader className="flex flex-row items-center justify-between pb-2">
              <CardTitle className="text-sm font-medium text-muted-foreground">
                {activeTab === 'business_pj' 
                  ? 'Faturamento (Receitas)' 
                  : activeTab === 'personal_pf' 
                  ? 'Entradas PF' 
                  : activeTab === 'transfer'
                  ? 'Entradas Neutras'
                  : 'Entradas Pendentes'}
              </CardTitle>
              <ArrowUpRight className="h-4 w-4 text-green-500" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold text-green-500">
                R$ {kpis.faturamento.toLocaleString('pt-BR', { minimumFractionDigits: 2 })}
              </div>
            </CardContent>
          </Card>

          <Card className="border-l-4 border-l-red-500">
            <CardHeader className="flex flex-row items-center justify-between pb-2">
              <CardTitle className="text-sm font-medium text-muted-foreground">
                {activeTab === 'business_pj' 
                  ? 'Gastos (Despesas)' 
                  : activeTab === 'personal_pf' 
                  ? 'Saídas PF' 
                  : activeTab === 'transfer'
                  ? 'Saídas Neutras'
                  : 'Saídas Pendentes'}
              </CardTitle>
              <ArrowDownLeft className="h-4 w-4 text-red-500" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold text-red-500">
                R$ {kpis.gastos.toLocaleString('pt-BR', { minimumFractionDigits: 2 })}
              </div>
            </CardContent>
          </Card>

          <Card className={`border-l-4 ${kpis.lucro >= 0 ? 'border-l-emerald-500' : 'border-l-rose-500'}`}>
            <CardHeader className="flex flex-row items-center justify-between pb-2">
              <CardTitle className="text-sm font-medium text-muted-foreground">
                {activeTab === 'business_pj' 
                  ? 'Lucro Líquido' 
                  : activeTab === 'personal_pf' 
                  ? 'Saldo PF' 
                  : activeTab === 'transfer'
                  ? 'Saldo Neutro'
                  : 'Saldo Pendente'}
              </CardTitle>
              <TrendingUp className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className={`text-2xl font-bold ${kpis.lucro >= 0 ? 'text-emerald-500' : 'text-rose-500'}`}>
                R$ {kpis.lucro.toLocaleString('pt-BR', { minimumFractionDigits: 2 })}
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Tabela de Histórico Persistido */}
        <Card>
          <CardHeader>
            <CardTitle>Histórico de Lançamentos</CardTitle>
            <CardDescription>
              Transações já conciliadas e gravadas no banco de dados para a origem selecionada.
            </CardDescription>
          </CardHeader>
          <CardContent className="p-0 overflow-x-auto">
            {fetchLoading ? (
              <div className="p-8 flex justify-center items-center">
                <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
              </div>
            ) : filteredHistory.length === 0 ? (
              <div className="p-8 text-center text-sm text-muted-foreground">
                Nenhuma transação encontrada no banco de dados para os filtros selecionados.
              </div>
            ) : (
              <table className="w-full text-left border-collapse text-sm">
                <thead>
                  <tr className="border-b bg-muted/40 font-medium text-muted-foreground">
                    <th className="p-4">Data</th>
                    <th className="p-4">Descrição</th>
                    <th className="p-4">Valor</th>
                    <th className="p-4 text-center">Classificação</th>
                    <th className="p-4 text-center">Ações</th>
                  </tr>
                </thead>
                <tbody>
                  {filteredHistory.map((tx) => {
                    const isPositive = tx.amount > 0;
                    return (
                      <tr key={tx.id} className="border-b hover:bg-muted/30 transition-colors">
                        <td className="p-4 font-mono">
                          {tx.transaction_date.split('-').reverse().join('/')}
                        </td>
                        <td className="p-4">
                          <div className="font-medium">{tx.description}</div>
                          {tx.fit_id && (
                            <div className="text-[10px] text-muted-foreground font-mono">
                              FITID: {tx.fit_id}
                            </div>
                          )}
                        </td>
                        <td className={`p-4 font-semibold ${isPositive ? 'text-green-500' : 'text-red-500'}`}>
                          R$ {tx.amount.toLocaleString('pt-BR', { minimumFractionDigits: 2 })}
                        </td>
                        <td className="p-4 text-center">
                          <div className="flex justify-center gap-1.5">
                            <Button
                              size="xs"
                              variant={tx.classification === 'business_pj' ? 'default' : 'outline'}
                              onClick={() => handleReclassifySaved(tx.id!, 'business_pj')}
                              className={tx.classification === 'business_pj' ? 'bg-emerald-600 hover:bg-emerald-700 text-white' : 'h-7 text-xs'}
                            >
                              PJ
                            </Button>
                            <Button
                              size="xs"
                              variant={tx.classification === 'personal_pf' ? 'default' : 'outline'}
                              onClick={() => handleReclassifySaved(tx.id!, 'personal_pf')}
                              className={tx.classification === 'personal_pf' ? 'bg-sky-600 hover:bg-sky-700 text-white' : 'h-7 text-xs'}
                            >
                              PF
                            </Button>
                            <Button
                              size="xs"
                              variant={tx.classification === 'transfer' ? 'default' : 'outline'}
                              onClick={() => handleReclassifySaved(tx.id!, 'transfer')}
                              className={tx.classification === 'transfer' ? 'bg-zinc-600 hover:bg-zinc-700 text-white' : 'h-7 text-xs'}
                            >
                              Neutro
                            </Button>
                          </div>
                        </td>
                        <td className="p-4 text-center">
                          <Button
                            size="xs"
                            variant="destructive"
                            onClick={() => handleDeleteSaved(tx.id!)}
                            className="h-7 text-xs flex items-center gap-1 mx-auto"
                          >
                            <Trash2 className="h-3 w-3" />
                            Excluir
                          </Button>
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            )}
          </CardContent>
        </Card>

        {/* Modal/Overlay de Importação e Conciliação */}
        {isImportModalOpen && (
          <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex justify-center items-center z-50 p-4">
            <div className="bg-background border rounded-lg max-w-4xl w-full max-h-[90vh] flex flex-col shadow-2xl">
              
              <div className="p-6 border-b flex justify-between items-center">
                <div>
                  <h3 className="text-lg font-bold">Conciliação de Extrato OFX</h3>
                  <p className="text-xs text-muted-foreground mt-0.5">
                    Origem selecionada: <span className="font-semibold">{activeSource === 'checking_account' ? 'Conta Corrente' : 'Cartão de Crédito'}</span>
                  </p>
                </div>
                <Button variant="ghost" size="icon" onClick={() => setIsImportModalOpen(false)}>
                  <X className="h-5 w-5" />
                </Button>
              </div>

              <div className="p-6 overflow-y-auto space-y-4 flex-1">
                {error && <div className="p-3 bg-red-500/10 text-red-500 border border-red-500/20 rounded text-sm">{error}</div>}
                {success && <div className="p-3 bg-green-500/10 text-green-500 border border-green-500/20 rounded text-sm">{success}</div>}

                {/* Formulário de Upload */}
                {tempTransactions.length === 0 && (
                  <form onSubmit={handleUploadOFX} className="space-y-4 py-4">
                    <div className="border-2 border-dashed border-muted rounded-xl p-8 flex flex-col items-center justify-center text-center gap-3">
                      <UploadCloud className="h-10 w-10 text-muted-foreground animate-pulse" />
                      <div>
                        <Label htmlFor="ofxFile" className="cursor-pointer text-sm font-semibold text-emerald-500 hover:underline">
                          Clique para selecionar
                        </Label>
                        <p className="text-xs text-muted-foreground mt-1">Apenas arquivos extrato no formato .ofx</p>
                      </div>
                      <Input
                        id="ofxFile"
                        type="file"
                        accept=".ofx"
                        required
                        onChange={handleFileChange}
                        className="hidden"
                      />
                      {file && <p className="text-xs font-mono bg-muted px-2 py-1 rounded text-foreground">{file.name}</p>}
                    </div>

                    <Button type="submit" disabled={importLoading || !file} className="w-full bg-emerald-600 hover:bg-emerald-700 text-white">
                      {importLoading ? (
                        <>
                          <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                          Processando Extrato...
                        </>
                      ) : (
                        'Processar Extrato'
                      )}
                    </Button>
                  </form>
                )}

                {/* Grid de Classificação das Transações Temporárias */}
                {tempTransactions.length > 0 && (
                  <div className="space-y-4">
                    <div className="border rounded-md overflow-hidden">
                      <table className="w-full text-left border-collapse text-sm">
                        <thead>
                          <tr className="border-b bg-muted/40 font-medium text-muted-foreground">
                            <th className="p-3">Data</th>
                            <th className="p-3">Descrição</th>
                            <th className="p-3">Valor</th>
                            <th className="p-3 text-center">Classificação</th>
                          </tr>
                        </thead>
                        <tbody>
                          {tempTransactions.map((tx, index) => {
                            const isPositive = tx.amount > 0;
                            let rowBg = '';
                            if (tx.is_duplicate) {
                              rowBg = 'bg-yellow-500/5 opacity-60';
                            } else if (tx.classification === 'business_pj') {
                              rowBg = 'bg-emerald-500/10 border-l-4 border-l-emerald-500';
                            } else if (tx.classification === 'personal_pf') {
                              rowBg = 'bg-sky-500/10 border-l-4 border-l-sky-500';
                            } else if (tx.classification === 'transfer') {
                              rowBg = 'bg-zinc-500/10 border-l-4 border-l-zinc-500';
                            }

                            return (
                              <tr key={index} className={`border-b transition-colors ${rowBg}`}>
                                <td className="p-3 font-mono">
                                  {tx.transaction_date.split('-').reverse().join('/')}
                                </td>
                                <td className="p-3">
                                  <div className="font-medium flex items-center gap-1.5">
                                    {tx.description}
                                    {tx.is_duplicate && (
                                      <span className="inline-flex items-center gap-0.5 px-1.5 py-0.5 rounded text-[9px] font-semibold bg-yellow-500/20 text-yellow-600 border border-yellow-500/30">
                                        <AlertTriangle className="h-2.5 w-2.5" />
                                        Duplicada
                                      </span>
                                    )}
                                  </div>
                                </td>
                                <td className={`p-3 font-semibold ${isPositive ? 'text-green-500' : 'text-red-500'}`}>
                                  R$ {tx.amount.toLocaleString('pt-BR', { minimumFractionDigits: 2 })}
                                </td>
                                <td className="p-3">
                                  <div className="flex justify-center gap-1.5">
                                    <Button
                                      size="xs"
                                      variant={tx.classification === 'business_pj' ? 'default' : 'outline'}
                                      onClick={() => handleClassifyTemp(index, 'business_pj')}
                                      className={tx.classification === 'business_pj' ? 'bg-emerald-600 hover:bg-emerald-700 text-white' : 'h-7 text-xs'}
                                    >
                                      PJ
                                    </Button>
                                    <Button
                                      size="xs"
                                      variant={tx.classification === 'personal_pf' ? 'default' : 'outline'}
                                      onClick={() => handleClassifyTemp(index, 'personal_pf')}
                                      className={tx.classification === 'personal_pf' ? 'bg-sky-600 hover:bg-sky-700 text-white' : 'h-7 text-xs'}
                                    >
                                      PF
                                    </Button>
                                    <Button
                                      size="xs"
                                      variant={tx.classification === 'transfer' ? 'default' : 'outline'}
                                      onClick={() => handleClassifyTemp(index, 'transfer')}
                                      className={tx.classification === 'transfer' ? 'bg-zinc-600 hover:bg-zinc-700 text-white' : 'h-7 text-xs'}
                                    >
                                      Neutro
                                    </Button>
                                  </div>
                                </td>
                              </tr>
                            );
                          })}
                        </tbody>
                      </table>
                    </div>
                  </div>
                )}
              </div>

              <div className="p-6 border-t flex justify-end gap-3 bg-muted/20">
                <Button variant="outline" onClick={() => setIsImportModalOpen(false)}>
                  Cancelar
                </Button>
                {tempTransactions.length > 0 && (
                  <Button 
                    onClick={handleConfirmImport} 
                    disabled={confirmLoading}
                    className="bg-emerald-600 hover:bg-emerald-700 text-white flex items-center gap-2"
                  >
                    {confirmLoading ? (
                      <>
                        <Loader2 className="h-4 w-4 animate-spin" />
                        Salvando...
                      </>
                    ) : (
                      <>
                        <CheckCircle className="h-4 w-4" />
                        Confirmar Fechamento
                      </>
                    )}
                  </Button>
                )}
              </div>

            </div>
          </div>
        )}

      </main>
    </div>
  );
}

// frontend-nuxt/pages/dashboard/receitas/index.vue
<template>
  <main class="flex-1 p-6 space-y-6 max-w-6xl w-full mx-auto">
    <!-- Cabeçalho da Página com Título e Botão de Ação -->
    <div class="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
      <div>
        <h1 class="text-2xl font-semibold tracking-tight text-gray-950 dark:text-white">Receitas e Fluxo de Caixa</h1>
        <p class="text-sm text-gray-500 mt-1">
          Acompanhe seu faturamento, controle despesas e faça conciliações rápidas via extrato.
        </p>
      </div>
      <UButton 
        icon="i-heroicons-cloud-arrow-up"
        class="flex items-center gap-2 font-medium"
        @click="openImportModal"
      >
        Importar Extrato OFX
      </UButton>
    </div>

    <!-- Abas Principais (Pendentes vs PJ vs PF vs Neutro) -->
    <div class="border-b border-gray-200 dark:border-zinc-800 flex gap-4 overflow-x-auto">
      <button
        v-for="tab in mainTabs"
        :key="tab.value"
        @click="activeTab = tab.value"
        class="pb-3 px-1 text-sm font-medium border-b-2 transition-colors whitespace-nowrap"
        :class="[
          activeTab === tab.value
            ? 'border-emerald-500 text-emerald-600 dark:text-emerald-400'
            : 'border-transparent text-gray-500 dark:text-zinc-400 hover:text-gray-700 hover:border-gray-300'
        ]"
      >
        {{ tab.label }}
      </button>
    </div>

    <!-- Abas Secundárias (Conta Corrente vs Cartão) -->
    <div class="flex bg-gray-100 dark:bg-zinc-800 p-1 rounded-lg self-start">
      <button
        v-for="src in sourceTabs"
        :key="src.value"
        @click="activeSource = src.value"
        class="flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-medium transition-colors"
        :class="[
          activeSource === src.value
            ? 'bg-white dark:bg-zinc-900 text-gray-950 dark:text-white shadow-sm'
            : 'text-gray-500 dark:text-zinc-400 hover:text-gray-900 dark:hover:text-white'
        ]"
      >
        <UIcon :name="src.icon" class="h-3.5 w-3.5" />
        {{ src.label }}
      </button>
    </div>

    <!-- Cards de KPIs (Atualizados com base nas seleções de abas) -->
    <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
      <UCard :ui="{ body: { padding: 'p-4 pb-3 flex flex-col gap-1 items-center text-center' } }">
        <div class="flex items-center gap-1.5 text-xs font-semibold text-gray-500">
          <UIcon name="i-heroicons-arrow-up-right" class="w-3.5 h-3.5 text-emerald-500 shrink-0" />
          <span>{{ faturamentoLabel }}</span>
        </div>
        <div class="text-2xl font-black tracking-tight text-gray-950 dark:text-white mt-1 font-mono">
          R$ {{ formatCurrency(kpis.faturamento) }}
        </div>
      </UCard>

      <UCard :ui="{ body: { padding: 'p-4 pb-3 flex flex-col gap-1 items-center text-center' } }">
        <div class="flex items-center gap-1.5 text-xs font-semibold text-gray-500">
          <UIcon name="i-heroicons-arrow-down-left" class="w-3.5 h-3.5 text-rose-500 shrink-0" />
          <span>{{ gastosLabel }}</span>
        </div>
        <div class="text-2xl font-black tracking-tight text-gray-950 dark:text-white mt-1 font-mono">
          R$ {{ formatCurrency(kpis.gastos) }}
        </div>
      </UCard>

      <UCard :ui="{ body: { padding: 'p-4 pb-3 flex flex-col gap-1 items-center text-center' } }">
        <div class="flex items-center gap-1.5 text-xs font-semibold text-gray-500">
          <UIcon name="i-heroicons-chart-bar" class="w-3.5 h-3.5 shrink-0" :class="[kpis.lucro >= 0 ? 'text-emerald-500' : 'text-rose-500']" />
          <span>{{ lucroLabel }}</span>
        </div>
        <div class="text-2xl font-black tracking-tight mt-1 font-mono" :class="[kpis.lucro >= 0 ? 'text-emerald-500' : 'text-rose-500']">
          R$ {{ formatCurrency(kpis.lucro) }}
        </div>
      </UCard>
    </div>

    <!-- Tabela de Histórico Persistido -->
    <div class="rounded-xl border border-gray-200 dark:border-zinc-800 bg-white dark:bg-zinc-950 shadow-sm overflow-hidden">
      <div class="p-6 border-b border-gray-200 dark:border-zinc-800 bg-gray-50/50 dark:bg-zinc-900/50">
        <h3 class="text-base font-semibold text-gray-950 dark:text-white">Histórico de Lançamentos</h3>
        <p class="text-xs text-gray-500 mt-1">
          Transações já conciliadas e gravadas no banco de dados para a origem selecionada.
        </p>
      </div>

      <div v-if="fetchLoading" class="p-12 flex justify-center items-center">
        <UIcon name="i-heroicons-arrow-path" class="h-6 w-6 animate-spin text-gray-500" />
      </div>

      <div v-else-if="filteredHistory.length === 0" class="p-12 text-center text-sm text-gray-500">
        Nenhuma transação encontrada no banco de dados para os filtros selecionados.
      </div>

      <div v-else class="overflow-x-auto w-full">
        <table class="w-full text-sm text-left">
          <thead class="bg-gray-50 dark:bg-zinc-900 text-xs font-semibold uppercase text-gray-500 dark:text-zinc-400 border-b border-gray-200 dark:border-zinc-800">
            <tr>
              <th class="px-4 py-3">Data</th>
              <th class="px-4 py-3">Descrição</th>
              <th class="px-4 py-3">Valor</th>
              <th class="px-4 py-3 text-center">Classificação</th>
              <th class="px-4 py-3 text-center">Ações</th>
            </tr>
          </thead>
          <tbody class="divide-y divide-gray-200 dark:divide-zinc-800">
            <tr 
              v-for="tx in filteredHistory" 
              :key="tx.id" 
              class="hover:bg-gray-50 dark:hover:bg-zinc-800/20 transition-colors"
            >
              <td class="px-4 py-3 font-mono text-gray-500 dark:text-zinc-400 whitespace-nowrap">
                {{ formatDate(tx.transaction_date) }}
              </td>
              <td class="px-4 py-3 whitespace-normal break-words max-w-[150px] sm:max-w-xs">
                <div class="font-medium text-gray-950 dark:text-white">{{ tx.description }}</div>
                <div v-if="tx.fit_id" class="text-[10px] text-gray-400 dark:text-zinc-500 font-mono mt-0.5">
                  FITID: {{ tx.fit_id }}
                </div>
              </td>
              <td class="px-4 py-3 font-semibold font-mono whitespace-nowrap" :class="[tx.amount > 0 ? 'text-emerald-500' : 'text-rose-500']">
                R$ {{ formatCurrency(tx.amount) }}
              </td>
              <td class="px-4 py-3">
                <div class="flex justify-center gap-1">
                  <UButton
                    size="xs"
                    :variant="tx.classification === 'business_pj' ? 'solid' : 'outline'"
                    color="emerald"
                    @click="handleReclassifySaved(tx.id!, 'business_pj')"
                  >
                    PJ
                  </UButton>
                  <UButton
                    size="xs"
                    :variant="tx.classification === 'personal_pf' ? 'solid' : 'outline'"
                    color="sky"
                    @click="handleReclassifySaved(tx.id!, 'personal_pf')"
                  >
                    PF
                  </UButton>
                  <UButton
                    size="xs"
                    :variant="tx.classification === 'transfer' ? 'solid' : 'outline'"
                    color="gray"
                    @click="handleReclassifySaved(tx.id!, 'transfer')"
                  >
                    Neutro
                  </UButton>
                </div>
              </td>
              <td class="px-4 py-3">
                <div class="flex justify-center">
                  <UButton
                    size="xs"
                    color="red"
                    variant="light"
                    icon="i-heroicons-trash"
                    class="flex items-center gap-1 font-medium"
                    @click="openDeleteDialog(tx.id!)"
                  >
                    Excluir
                  </UButton>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <!-- Modal/Dialog de Importação e Conciliação -->
    <UModal v-model="isImportModalOpen" prevent-close :ui="{ width: 'sm:max-w-2xl md:max-w-3xl lg:max-w-4xl' }">
      <div class="flex flex-col max-h-[90vh] overflow-hidden bg-white dark:bg-zinc-950 border border-gray-200 dark:border-zinc-800 rounded-lg shadow-xl">
        <div class="p-6 pb-4 border-b border-gray-200 dark:border-zinc-800 shrink-0">
          <h3 class="text-lg font-bold text-gray-900 dark:text-white">Conciliação de Extrato OFX</h3>
          <p class="text-xs text-gray-500 mt-1">
            Origem selecionada: <span class="font-semibold">{{ activeSource === 'checking_account' ? 'Conta Corrente' : 'Cartão de Crédito' }}</span>
          </p>
        </div>

        <div class="p-6 overflow-y-auto space-y-4 flex-1">
          <!-- Formulário de Upload -->
          <form v-if="tempTransactions.length === 0" @submit.prevent="handleUploadOFX" class="space-y-4 py-4">
            <div class="border border-dashed border-gray-300 dark:border-zinc-700 rounded-xl p-8 flex flex-col items-center justify-center text-center gap-3 bg-gray-50 dark:bg-zinc-900/50">
              <UIcon name="i-heroicons-cloud-arrow-up" class="h-8 w-8 text-gray-400 animate-pulse" />
              <div>
                <label for="ofxFile" class="cursor-pointer text-sm font-semibold text-emerald-500 hover:underline">
                  Clique para selecionar o arquivo
                </label>
                <p class="text-xs text-gray-500 mt-1">Apenas arquivos no formato .ofx</p>
              </div>
              <input
                id="ofxFile"
                type="file"
                accept=".ofx"
                required
                class="hidden"
                @change="handleFileChange"
              />
              <p v-if="file" class="text-xs font-mono bg-gray-100 dark:bg-zinc-800 border border-gray-200 dark:border-zinc-700 px-2.5 py-1 rounded-md text-gray-700 dark:text-zinc-300 mt-2">
                {{ file.name }}
              </p>
            </div>

            <UButton type="submit" block :loading="importLoading" :disabled="!file">
              Carregar Extrato
            </UButton>
          </form>

          <!-- Lista de lançamentos a classificar -->
          <div v-else class="space-y-4">
            <div class="border border-gray-200 dark:border-zinc-800 rounded-md overflow-hidden bg-white dark:bg-zinc-900">
              <div class="overflow-x-auto">
                <table class="w-full text-sm text-left">
                  <thead class="bg-gray-50 dark:bg-zinc-950 text-xs font-semibold uppercase text-gray-500">
                    <tr>
                      <th class="px-4 py-3">Data</th>
                      <th class="px-4 py-3">Descrição</th>
                      <th class="px-4 py-3">Valor</th>
                      <th class="px-4 py-3 text-center">Classificação</th>
                    </tr>
                  </thead>
                  <tbody class="divide-y divide-gray-200 dark:divide-zinc-800">
                    <tr 
                      v-for="(tx, index) in tempTransactions" 
                      :key="index"
                      :class="[
                        tx.is_duplicate 
                          ? 'bg-amber-500/5 opacity-70' 
                          : tx.classification === 'business_pj'
                          ? 'bg-emerald-500/5 border-l-2 border-l-emerald-500'
                          : tx.classification === 'personal_pf'
                          ? 'bg-sky-500/5 border-l-2 border-l-sky-500'
                          : tx.classification === 'transfer'
                          ? 'bg-zinc-500/5 border-l-2 border-l-zinc-500'
                          : ''
                      ]"
                    >
                      <td class="px-4 py-3 font-mono text-gray-500 dark:text-zinc-400 whitespace-nowrap">
                        {{ formatDate(tx.transaction_date) }}
                      </td>
                      <td class="px-4 py-3 whitespace-normal break-words max-w-[150px] sm:max-w-xs">
                        <div class="font-medium flex items-center gap-1.5 flex-wrap">
                          <span>{{ tx.description }}</span>
                          <span v-if="tx.is_duplicate" class="inline-flex items-center gap-1 px-1.5 py-0.5 rounded text-[10px] font-medium bg-amber-50 dark:bg-amber-950/30 text-amber-600 dark:text-amber-400 border border-amber-200 dark:border-amber-900/50">
                            <UIcon name="i-heroicons-exclamation-triangle" class="h-3 w-3" />
                            Duplicada
                          </span>
                        </div>
                      </td>
                      <td class="px-4 py-3 font-semibold font-mono whitespace-nowrap" :class="[tx.amount > 0 ? 'text-emerald-500' : 'text-rose-500']">
                        R$ {{ formatCurrency(tx.amount) }}
                      </td>
                      <td class="px-4 py-3">
                        <div class="flex justify-center gap-1">
                          <UButton
                            size="xs"
                            :variant="tx.classification === 'business_pj' ? 'solid' : 'outline'"
                            color="emerald"
                            @click="handleClassifyTemp(index, 'business_pj')"
                          >
                            PJ
                          </UButton>
                          <UButton
                            size="xs"
                            :variant="tx.classification === 'personal_pf' ? 'solid' : 'outline'"
                            color="sky"
                            @click="handleClassifyTemp(index, 'personal_pf')"
                          >
                            PF
                          </UButton>
                          <UButton
                            size="xs"
                            :variant="tx.classification === 'transfer' ? 'solid' : 'outline'"
                            color="gray"
                            @click="handleClassifyTemp(index, 'transfer')"
                          >
                            Neutro
                          </UButton>
                        </div>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>

        <div class="p-6 border-t border-gray-200 dark:border-zinc-800 flex justify-end gap-3 bg-gray-50 dark:bg-zinc-900/20 shrink-0">
          <UButton color="gray" variant="ghost" @click="isImportModalOpen = false">
            Cancelar
          </UButton>
          <UButton 
            v-if="tempTransactions.length > 0"
            color="emerald"
            icon="i-heroicons-check-circle"
            :loading="confirmLoading"
            @click="handleConfirmImport"
          >
            Confirmar Fechamento
          </UButton>
        </div>
      </div>
    </UModal>

    <!-- Dialog de Confirmação de Exclusão (Dupla Confirmação) -->
    <UModal v-model="isDeleteDialogOpen" :ui="{ width: 'sm:max-w-[425px]' }">
      <div class="p-6 bg-white dark:bg-zinc-900 rounded-lg shadow-xl border border-gray-200 dark:border-zinc-800">
        <div class="flex items-center gap-2 text-red-600 dark:text-red-500 mb-1">
          <UIcon name="i-heroicons-exclamation-triangle" class="h-5 w-5 animate-bounce" />
          <h3 class="text-lg font-bold">Excluir Lançamento</h3>
        </div>
        
        <div class="pt-2 text-sm text-gray-500 dark:text-zinc-400 text-left">
          Você está prestes a excluir esta transação permanentemente. Esta ação atualizará seus relatórios financeiros.
        </div>
        
        <p class="text-[11px] text-gray-400 dark:text-zinc-500 pt-1.5 font-semibold text-left">
          Esta ação é irreversível e removerá permanentemente os registros do banco de dados.
        </p>
        
        <div class="pt-4 flex justify-end gap-3">
          <UButton 
            color="gray" 
            variant="ghost" 
            @click="isDeleteDialogOpen = false"
          >
            Cancelar
          </UButton>
          <UButton 
            color="red" 
            @click="confirmDelete"
          >
            Confirmar Exclusão
          </UButton>
        </div>
      </div>
    </UModal>
  </main>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'

interface TransactionPayload {
  id?: number
  transaction_date: string
  description: string
  amount: number
  source: 'checking_account' | 'credit_card'
  classification: 'pending' | 'business_pj' | 'personal_pf' | 'transfer'
  fit_id?: string | null
  is_duplicate?: boolean
}

const activeTab = ref<'business_pj' | 'personal_pf' | 'transfer' | 'pending'>('business_pj')
const activeSource = ref<'checking_account' | 'credit_card'>('checking_account')

const history = ref<TransactionPayload[]>([])
const tempTransactions = ref<TransactionPayload[]>([])

const isImportModalOpen = ref(false)
const file = ref<File | null>(null)

const fetchLoading = ref(false)
const importLoading = ref(false)
const confirmLoading = ref(false)

const isDeleteDialogOpen = ref(false)
const transactionToDelete = ref<number | null>(null)

const { apiFetch } = useAuth()
const toast = useToast()

const mainTabs = [
  { label: 'Pendentes', value: 'pending' },
  { label: 'Pessoa Jurídica (PJ)', value: 'business_pj' },
  { label: 'Pessoa Física (PF)', value: 'personal_pf' },
  { label: 'Neutro / Transferências', value: 'transfer' }
]

const sourceTabs = [
  { label: 'Conta Corrente', value: 'checking_account', icon: 'i-heroicons-wallet' },
  { label: 'Cartão de Crédito', value: 'credit_card', icon: 'i-heroicons-credit-card' }
]

// Labels dinâmicos para os cards baseados na aba atual
const faturamentoLabel = computed(() => {
  switch (activeTab.value) {
    case 'business_pj': return 'Faturamento (PJ)'
    case 'personal_pf': return 'Entradas (PF)'
    case 'transfer': return 'Entradas (Neutras)'
    default: return 'Entradas (Pendentes)'
  }
})

const gastosLabel = computed(() => {
  switch (activeTab.value) {
    case 'business_pj': return 'Gastos (PJ)'
    case 'personal_pf': return 'Saídas (PF)'
    case 'transfer': return 'Saídas (Neutras)'
    default: return 'Saídas (Pendentes)'
  }
})

const lucroLabel = computed(() => {
  switch (activeTab.value) {
    case 'business_pj': return 'Lucro Líquido'
    case 'personal_pf': return 'Saldo (PF)'
    case 'transfer': return 'Saldo (Neutro)'
    default: return 'Saldo (Pendente)'
  }
})

// Busca histórico
const fetchHistory = async () => {
  fetchLoading.value = true
  try {
    const response: any = await apiFetch('/transactions', { method: 'GET' })
    if (response && response.success) {
      history.value = response.data || []
    } else {
      toast.add({
        title: 'Erro ao carregar histórico',
        description: response?.message || 'Falha ao buscar dados',
        color: 'red'
      })
    }
  } catch (err: any) {
    toast.add({
      title: 'Erro de conexão',
      description: err.message || 'Falha ao buscar dados no backend',
      color: 'red'
    })
  } finally {
    fetchLoading.value = false
  }
}

// Filtra histórico
const filteredHistory = computed(() => {
  return history.value.filter(
    (tx) => tx.source === activeSource.value && tx.classification === activeTab.value
  )
})

// KPIs baseados nos lançamentos filtrados
const kpis = computed(() => {
  let faturamento = 0
  let gastos = 0

  filteredHistory.value.forEach((tx) => {
    if (tx.amount > 0) {
      faturamento += tx.amount
    } else {
      gastos += Math.abs(tx.amount)
    }
  })

  return {
    faturamento,
    gastos,
    lucro: faturamento - gastos
  }
})

// Abre modal de importação
const openImportModal = () => {
  tempTransactions.value = []
  file.value = null
  isImportModalOpen.value = true
}

// Controla upload
const handleFileChange = (e: Event) => {
  const target = e.target as HTMLInputElement
  if (target.files && target.files.length > 0) {
    file.value = target.files[0]
  }
}

const handleUploadOFX = async () => {
  if (!file.value) return

  importLoading.value = true
  tempTransactions.value = []

  const formData = new FormData()
  formData.append('source', activeSource.value)
  formData.append('file', file.value)

  try {
    const response: any = await apiFetch('/transactions/parse', {
      method: 'POST',
      body: formData
    })

    if (response && response.success) {
      tempTransactions.value = response.data || []
      toast.add({
        title: 'Arquivo processado!',
        description: 'Extrato processado com sucesso. Classifique os lançamentos.',
        color: 'green'
      })
    } else {
      toast.add({
        title: 'Falha no upload',
        description: response?.message || 'Erro ao processar o arquivo.',
        color: 'red'
      })
    }
  } catch (err: any) {
    toast.add({
      title: 'Erro de conexão',
      description: err.message || 'Erro ao processar arquivo.',
      color: 'red'
    })
  } finally {
    importLoading.value = false
  }
}

// Classifica lançamento temporário na memória
const handleClassifyTemp = (index: number, classification: 'business_pj' | 'personal_pf' | 'transfer') => {
  tempTransactions.value = tempTransactions.value.map((tx, idx) => 
    idx === index ? { ...tx, classification } : tx
  )
}

// Confirma importação
const handleConfirmImport = async () => {
  confirmLoading.value = true
  try {
    const response: any = await apiFetch('/transactions/confirm', {
      method: 'POST',
      body: { transactions: tempTransactions.value }
    })

    if (response && response.success) {
      toast.add({
        title: 'Lançamentos salvos!',
        description: 'Transações salvas e conciliação realizada com sucesso.',
        color: 'green'
      })
      tempTransactions.value = []
      file.value = null
      isImportModalOpen.value = false
      await fetchHistory()
    } else {
      toast.add({
        title: 'Erro ao salvar',
        description: response?.message || 'Falha ao salvar lançamentos.',
        color: 'red'
      })
    }
  } catch (err: any) {
    toast.add({
      title: 'Erro de conexão',
      description: err.message || 'Falha ao salvar lançamentos.',
      color: 'red'
    })
  } finally {
    confirmLoading.value = false
  }
}

// Reclassifica lançamento salvo no banco
const handleReclassifySaved = async (id: number, classification: 'business_pj' | 'personal_pf' | 'transfer') => {
  try {
    const response: any = await apiFetch(`/transactions/${id}/classify`, {
      method: 'PATCH',
      body: { classification }
    })

    if (response && response.success) {
      history.value = history.value.map((tx) =>
        tx.id === id ? { ...tx, classification } : tx
      )
      toast.add({
        title: 'Classificação atualizada',
        description: 'Classificação atualizada com sucesso.',
        color: 'green'
      })
    } else {
      toast.add({
        title: 'Erro ao reclassificar',
        description: response?.message || 'Erro ao alterar classificação.',
        color: 'red'
      })
    }
  } catch (err: any) {
    toast.add({
      title: 'Erro de conexão',
      description: err.message || 'Erro ao alterar classificação.',
      color: 'red'
    })
  }
}

// Exclui lançamento com dupla confirmação
const openDeleteDialog = (id: number) => {
  transactionToDelete.value = id
  isDeleteDialogOpen.value = true
}

const confirmDelete = async () => {
  if (transactionToDelete.value === null) return
  const id = transactionToDelete.value
  isDeleteDialogOpen.value = false
  transactionToDelete.value = null

  try {
    const response: any = await apiFetch(`/transactions/${id}`, {
      method: 'DELETE'
    })

    if (response && response.success) {
      history.value = history.value.filter((tx) => tx.id !== id)
      toast.add({
        title: 'Lançamento excluído',
        description: 'Transação excluída com sucesso.',
        color: 'green'
      })
    } else {
      toast.add({
        title: 'Erro ao excluir',
        description: response?.message || 'Erro ao excluir transação.',
        color: 'red'
      })
    }
  } catch (err: any) {
    toast.add({
      title: 'Erro de conexão',
      description: err.message || 'Erro de conexão ao excluir transação.',
      color: 'red'
    })
  }
}

// Formatadores
const formatDate = (dateStr: string) => {
  if (!dateStr) return ''
  return dateStr.split('-').reverse().join('/')
}

const formatCurrency = (val: number) => {
  return val.toLocaleString('pt-BR', { minimumFractionDigits: 2, maximumFractionDigits: 2 })
}

onMounted(() => {
  fetchHistory()
})
</script>
