// frontend-nuxt/pages/register.vue
<template>
  <main class="min-h-screen flex items-center justify-center p-4 bg-gray-50 dark:bg-zinc-900">
    <div class="w-full max-w-sm space-y-6">
      <!-- Logo and Intro -->
      <div class="text-center space-y-2 select-none animate-fade-in">
        <div class="inline-flex w-10 h-10 rounded-xl bg-emerald-500 text-white items-center justify-center font-bold text-base shadow-sm">
          MF
        </div>
        <h1 class="text-xl font-bold tracking-tight text-gray-950 dark:text-white">Criar Nova Conta</h1>
        <p class="text-xs text-gray-400">
          Gerencie suas finanças PJ e PF no mesmo lugar.
        </p>
      </div>

      <!-- Main Register Card -->
      <UCard 
        :ui="{ 
          base: 'border border-gray-100 dark:border-zinc-800/80 bg-white dark:bg-zinc-950 shadow-none rounded-2xl',
          body: { padding: 'p-6 space-y-4' }
        }"
      >
        <div v-if="error" class="text-xs text-red-500 bg-red-50 dark:bg-red-950/20 px-3 py-2 rounded-lg border border-red-100 dark:border-red-900/50">
          {{ error }}
        </div>

        <div v-if="success" class="text-xs text-green-500 bg-green-50 dark:bg-green-950/20 px-3 py-2 rounded-lg border border-green-100 dark:border-green-900/50">
          {{ success }}
        </div>

        <form @submit.prevent="handleSubmit" class="space-y-4">
          <UFormGroup label="Nome Completo" name="name" :ui="{ label: { wrapper: 'mb-1', text: 'text-[10px] font-bold uppercase tracking-wider text-gray-400' } }">
            <UInput
              id="name"
              v-model="name"
              type="text"
              placeholder="Carlos Silva"
              required
              size="md"
              :disabled="loading"
              :ui="{ rounded: 'rounded-lg' }"
            />
          </UFormGroup>

          <UFormGroup label="E-mail de Acesso" name="email" :ui="{ label: { wrapper: 'mb-1', text: 'text-[10px] font-bold uppercase tracking-wider text-gray-400' } }">
            <UInput
              id="email"
              v-model="email"
              type="email"
              placeholder="carlos@email.com"
              required
              size="md"
              :disabled="loading"
              :ui="{ rounded: 'rounded-lg' }"
            />
          </UFormGroup>

          <UFormGroup label="CNPJ (Opcional)" name="cnpj" :ui="{ label: { wrapper: 'mb-1', text: 'text-[10px] font-bold uppercase tracking-wider text-gray-400' } }">
            <UInput
              id="cnpj"
              v-model="cnpj"
              type="text"
              placeholder="12.345.678/0001-99"
              size="md"
              :disabled="loading"
              :ui="{ rounded: 'rounded-lg' }"
            />
          </UFormGroup>

          <UFormGroup label="Senha (mínimo 6 dígitos)" name="password" :ui="{ label: { wrapper: 'mb-1', text: 'text-[10px] font-bold uppercase tracking-wider text-gray-400' } }">
            <UInput
              id="password"
              v-model="password"
              type="password"
              placeholder="••••••••"
              required
              size="md"
              :disabled="loading"
              :ui="{ rounded: 'rounded-lg' }"
            />
          </UFormGroup>

          <UButton
            type="submit"
            block
            color="emerald"
            class="text-xs font-semibold uppercase tracking-wider py-2.5 rounded-lg mt-2"
            :loading="loading"
          >
            Cadastrar Conta
          </UButton>
        </form>
      </UCard>

      <!-- Footer navigation links -->
      <p class="text-center text-xs text-gray-400 select-none">
        Já possui cadastro? 
        <NuxtLink to="/login" class="text-emerald-500 hover:text-emerald-600 font-semibold underline">
          Entrar na sua conta
        </NuxtLink>
      </p>
    </div>
  </main>
</template>

<script setup lang="ts">
import { ref } from 'vue'

definePageMeta({
  layout: false
})

const name = ref('')
const email = ref('')
const cnpj = ref('')
const password = ref('')
const error = ref('')
const success = ref('')
const loading = ref(false)

const { register } = useAuth()

const handleSubmit = async () => {
  error.value = ''
  success.value = ''
  loading.value = true

  if (password.value.length < 6) {
    error.value = 'A senha deve conter no mínimo 6 caracteres.'
    loading.value = false
    return
  }

  const result = await register({
    name: name.value,
    email: email.value,
    cnpj: cnpj.value || null,
    password: password.value
  })

  if (result.success) {
    success.value = 'Cadastro realizado com sucesso! Conectando...'
    setTimeout(() => {
      navigateTo('/dashboard')
    }, 1200)
  } else {
    error.value = result.message || 'Falha ao realizar cadastro. Tente novamente.'
    loading.value = false
  }
}
</script>

// nextjs/app/register/page.tsx
"use client";

import React, { useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { registerAccountant } from "@/services/auth";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card } from "@/components/ui/card";
import { toast } from "sonner";

export default function RegisterPage() {
  const router = useRouter();

  // Form state
  const [formData, setFormData] = useState({
    name: "",
    email: "",
    crc: "",
    office_name: "",
    password: "",
  });

  // UI state
  const [loading, setLoading] = useState(false);
  const [errors, setErrors] = useState<{ [key: string]: string[] }>({});

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
    // Clear field-specific error when user types
    if (errors[name]) {
      setErrors((prev) => {
        const next = { ...prev };
        delete next[name];
        return next;
      });
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setErrors({});

    const response = await registerAccountant(formData);

    if (response.success) {
      const successMsg = response.message || "Cadastro realizado com sucesso.";
      toast.success(successMsg);
      setTimeout(() => {
        router.push(`/login?message=${encodeURIComponent(successMsg)}`);
      }, 1500);
    } else {
      setLoading(false);
      if (response.data && typeof response.data === "object") {
        setErrors(response.data);
      } else {
        toast.error(response.message || "Erro inesperado ao realizar o cadastro.");
      }
    }
  };

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 font-sans flex items-center justify-center p-4 relative overflow-hidden">
      {/* Background Glows */}
      <div className="absolute top-1/4 left-1/4 w-[500px] h-[500px] bg-emerald-500/10 rounded-full blur-3xl pointer-events-none animate-pulse" />
      <div className="absolute bottom-1/4 right-1/4 w-[500px] h-[500px] bg-green-500/10 rounded-full blur-3xl pointer-events-none" />

      <div className="w-full max-w-lg space-y-6 relative z-10">
        {/* Logo and title */}
        <div className="text-center space-y-2 select-none">
          <div className="inline-flex w-12 h-12 rounded-2xl bg-gradient-to-tr from-emerald-500 to-green-600 text-white items-center justify-center font-bold text-lg shadow-lg shadow-emerald-500/20 mb-2">
            MF
          </div>
          <h1 className="text-2xl font-bold tracking-tight text-white">MEI Finance</h1>
          <p className="text-sm text-slate-400">
            A plataforma definitiva para contadores de MEIs.
          </p>
        </div>

        <Card className="bg-slate-900/35 backdrop-blur-md border border-slate-800/80 rounded-2xl p-6 sm:p-8 shadow-2xl shadow-emerald-500/2 hover:border-emerald-500/20 transition-all duration-300">
          <div className="space-y-4">
            <div className="space-y-1.5 text-center">
              <h2 className="text-2xl font-bold tracking-tight text-white">
                Criar Nova Conta
              </h2>
              <p className="text-slate-400 text-xs">
                Já possui uma conta?{" "}
                <Link
                  href="/login"
                  className="font-semibold text-emerald-400 hover:text-emerald-300 transition-colors hover:underline"
                >
                  Faça login
                </Link>
              </p>
            </div>

            <form onSubmit={handleSubmit} className="grid gap-4 pt-2">
              {/* Name */}
              <div className="grid gap-1.5 text-left">
                <Label htmlFor="name" className="text-slate-300 text-xs font-semibold uppercase tracking-wider">Nome Completo</Label>
                <Input
                  id="name"
                  name="name"
                  type="text"
                  placeholder="Seu nome completo"
                  value={formData.name}
                  onChange={handleChange}
                  className="w-full bg-slate-950/60 border-slate-800 rounded-xl px-4 py-6 text-white placeholder-slate-500 focus-visible:border-emerald-500 focus-visible:ring-emerald-500/20 text-sm transition-all"
                />
                {errors.name && (
                  <p className="text-destructive text-xs font-medium">{errors.name[0]}</p>
                )}
              </div>

              {/* Email */}
              <div className="grid gap-1.5 text-left">
                <Label htmlFor="email" className="text-slate-300 text-xs font-semibold uppercase tracking-wider">Endereço de E-mail</Label>
                <Input
                  id="email"
                  name="email"
                  type="email"
                  placeholder="nome@empresa.com"
                  value={formData.email}
                  onChange={handleChange}
                  className="w-full bg-slate-950/60 border-slate-800 rounded-xl px-4 py-6 text-white placeholder-slate-500 focus-visible:border-emerald-500 focus-visible:ring-emerald-500/20 text-sm transition-all"
                />
                {errors.email && (
                  <p className="text-destructive text-xs font-medium">{errors.email[0]}</p>
                )}
              </div>

              {/* CRC and Office Name in 2 columns */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                {/* CRC */}
                <div className="grid gap-1.5 text-left">
                  <Label htmlFor="crc" className="text-slate-300 text-xs font-semibold uppercase tracking-wider">Registro CRC</Label>
                  <Input
                    id="crc"
                    name="crc"
                    type="text"
                    placeholder="UF-000000/O"
                    value={formData.crc}
                    onChange={handleChange}
                    className="w-full bg-slate-950/60 border-slate-800 rounded-xl px-4 py-6 text-white placeholder-slate-500 focus-visible:border-emerald-500 focus-visible:ring-emerald-500/20 text-sm transition-all"
                  />
                  {errors.crc && (
                    <p className="text-destructive text-xs font-medium">{errors.crc[0]}</p>
                  )}
                </div>

                {/* Office Name */}
                <div className="grid gap-1.5 text-left">
                  <Label htmlFor="office_name" className="text-slate-300 text-xs font-semibold uppercase tracking-wider">Nome do Escritório</Label>
                  <Input
                    id="office_name"
                    name="office_name"
                    type="text"
                    placeholder="Escritório Contábil"
                    value={formData.office_name}
                    onChange={handleChange}
                    className="w-full bg-slate-950/60 border-slate-800 rounded-xl px-4 py-6 text-white placeholder-slate-500 focus-visible:border-emerald-500 focus-visible:ring-emerald-500/20 text-sm transition-all"
                  />
                  {errors.office_name && (
                    <p className="text-destructive text-xs font-medium">{errors.office_name[0]}</p>
                  )}
                </div>
              </div>

              {/* Password */}
              <div className="grid gap-1.5 text-left">
                <Label htmlFor="password" className="text-slate-300 text-xs font-semibold uppercase tracking-wider">Senha</Label>
                <Input
                  id="password"
                  name="password"
                  type="password"
                  placeholder="Mínimo 8 caracteres"
                  value={formData.password}
                  onChange={handleChange}
                  className="w-full bg-slate-950/60 border-slate-800 rounded-xl px-4 py-6 text-white placeholder-slate-500 focus-visible:border-emerald-500 focus-visible:ring-emerald-500/20 text-sm transition-all"
                />
                {errors.password && (
                  <p className="text-destructive text-xs font-medium">{errors.password[0]}</p>
                )}
              </div>

              {/* Submit Button */}
              <Button
                type="submit"
                disabled={loading}
                className="w-full mt-2 bg-gradient-to-r from-emerald-600 to-green-600 hover:from-emerald-500 hover:to-green-500 text-white font-semibold rounded-xl py-6 transition-all flex items-center justify-center gap-2 text-sm focus-visible:ring-emerald-500/20 shadow-lg shadow-emerald-500/10 cursor-pointer active:scale-[0.98]"
              >
                {loading ? (
                  <>
                    <svg className="animate-spin h-5 w-5 text-white" fill="none" viewBox="0 0 24 24">
                      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
                    </svg>
                    <span>Processando...</span>
                  </>
                ) : (
                  <span>Criar minha conta</span>
                )}
              </Button>
            </form>
          </div>
        </Card>

        <p className="text-center text-xs text-slate-500 select-none">
          &copy; {new Date().getFullYear()} MEI Finance. Todos os direitos reservados.
        </p>
      </div>
    </div>
  );
}
