// frontend-nuxt/pages/login.vue
<template>
  <main class="min-h-screen flex items-center justify-center p-4">
    <div class="w-full max-w-md">
      <UCard>
        <template #header>
          <div class="text-center">
            <h1 class="text-3xl font-bold tracking-tight">MEI Finance</h1>
            <p class="text-sm text-gray-500 mt-1">
              Gerencie suas contas PJ e PF de forma inteligente
            </p>
          </div>
        </template>

        <div v-if="error" class="mb-4 text-sm text-red-500 bg-red-50 dark:bg-red-950/20 p-2.5 rounded">
          {{ error }}
        </div>

        <div v-if="success" class="mb-4 text-sm text-green-500 bg-green-50 dark:bg-green-950/20 p-2.5 rounded">
          {{ success }}
        </div>

        <form @submit.prevent="handleSubmit" class="space-y-4">
          <UFormGroup label="E-mail" name="email" required>
            <UInput
              id="email"
              v-model="email"
              type="email"
              placeholder="Ex: carlos@email.com"
              required
              :disabled="loading"
            />
          </UFormGroup>

          <UFormGroup label="Senha" name="password" required>
            <UInput
              id="password"
              v-model="password"
              type="password"
              placeholder="••••••••"
              required
              :disabled="loading"
            />
          </UFormGroup>

          <UButton
            type="submit"
            block
            :loading="loading"
          >
            Entrar
          </UButton>
        </form>

        <template #footer>
          <div class="text-center text-xs text-gray-500">
            Ainda não tem cadastro? 
            <NuxtLink to="/register" class="text-primary hover:underline font-semibold">
              Criar conta
            </NuxtLink>
          </div>
        </template>
      </UCard>
    </div>
  </main>
</template>

<script setup lang="ts">
import { ref } from 'vue'

definePageMeta({
  layout: false
})

const email = ref('')
const password = ref('')
const error = ref('')
const success = ref('')
const loading = ref(false)

const { login } = useAuth()

const handleSubmit = async () => {
  error.value = ''
  success.value = ''
  loading.value = true

  const result = await login(email.value, password.value)
  if (result.success) {
    success.value = 'Acesso concedido! Carregando painel...'
    setTimeout(() => {
      navigateTo('/dashboard')
    }, 1500)
  } else {
    error.value = result.message || 'Erro ao tentar acessar. Tente novamente.'
    loading.value = false
  }
}
</script>

// frontend/src/app/login/page.tsx
'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { signIn } from 'next-auth/react';
import { Loader2 } from 'lucide-react';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Button } from '@/components/ui/button';

export default function LoginPage() {
  const router = useRouter();
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setSuccess('');
    setLoading(true);

    try {
      const result = await signIn('credentials', {
        email,
        password,
        redirect: false,
      });

      if (result?.error) {
        setError(result.error);
        setLoading(false);
      } else if (result?.ok) {
        setSuccess('Acesso concedido! Carregando painel...');
        setTimeout(() => {
          router.push('/dashboard');
        }, 1500);
      }
    } catch (err: any) {
      setError('Ocorreu um erro ao tentar acessar. Tente novamente.');
      setLoading(false);
    }
  };

  return (
    <main className="min-h-screen flex items-center justify-center p-4">
      <div className="w-full max-w-md">
        <Card>
          <CardHeader className="text-center">
            <CardTitle className="text-3xl font-bold">MEI Finance</CardTitle>
            <CardDescription>
              Gerencie suas contas PJ e PF de forma inteligente
            </CardDescription>
          </CardHeader>
          
          <CardContent>
            {error && (
              <div className="mb-4 text-sm text-red-500">
                {error}
              </div>
            )}

            {success && (
              <div className="mb-4 text-sm text-green-500">
                {success}
              </div>
            )}

            <form onSubmit={handleSubmit} className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="email">E-mail</Label>
                <Input
                  id="email"
                  type="email"
                  required
                  disabled={loading}
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  placeholder="Ex: carlos@email.com"
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="password">Senha</Label>
                <Input
                  id="password"
                  type="password"
                  required
                  disabled={loading}
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  placeholder="••••••••"
                />
              </div>

              <Button type="submit" className="w-full" disabled={loading}>
                {loading ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Acessando...
                  </>
                ) : (
                  'Entrar'
                )}
              </Button>
            </form>
          </CardContent>
          
          <CardFooter className="flex justify-center border-t pt-4">
            <p className="text-xs text-muted-foreground">
              Ainda não tem cadastro?{' '}
              <Link href="/register" className="text-primary hover:underline font-semibold">
                Criar conta
              </Link>
            </p>
          </CardFooter>
        </Card>
      </div>
    </main>
  );
}
