// frontend-nuxt/pages/login.vue
<template>
  <main class="min-h-screen flex items-center justify-center p-4 bg-gray-50 dark:bg-zinc-900">
    <div class="w-full max-w-sm space-y-6">
      <!-- Logo and Intro -->
      <div class="text-center space-y-2 select-none animate-fade-in">
        <div class="inline-flex w-10 h-10 rounded-xl bg-emerald-500 text-white items-center justify-center font-bold text-base shadow-sm">
          MF
        </div>
        <h1 class="text-xl font-bold tracking-tight text-gray-950 dark:text-white">Acessar MEI Finance</h1>
        <p class="text-xs text-gray-400">
          Gerencie suas finanças PJ e PF no mesmo lugar.
        </p>
      </div>

      <!-- Main Login Card -->
      <UCard 
        :ui="{ 
          base: 'border border-gray-100 dark:border-zinc-800/80 bg-white dark:bg-zinc-950 shadow-none rounded-2xl',
          body: { padding: 'p-6 space-y-4' }
        }"
      >
        <div v-if="error" class="text-xs text-red-500 bg-red-50 dark:bg-red-950/20 px-3 py-2 rounded-lg border border-red-100 dark:border-red-900/50">
          {{ error }}
        </div>

        <div v-if="success" class="text-xs text-green-500 bg-green-50 dark:bg-green-950/20 px-3 py-2 rounded-lg border border-green-100 dark:border-green-900/50">
          {{ success }}
        </div>

        <form @submit.prevent="handleSubmit" class="space-y-4">
          <UFormGroup label="E-mail" name="email" :ui="{ label: { wrapper: 'mb-1', text: 'text-[10px] font-bold uppercase tracking-wider text-gray-400' } }">
            <UInput
              id="email"
              v-model="email"
              type="email"
              placeholder="carlos@email.com"
              required
              size="md"
              :disabled="loading"
              :ui="{ rounded: 'rounded-lg' }"
            />
          </UFormGroup>

          <UFormGroup label="Senha" name="password" :ui="{ label: { wrapper: 'mb-1', text: 'text-[10px] font-bold uppercase tracking-wider text-gray-400' } }">
            <UInput
              id="password"
              v-model="password"
              type="password"
              placeholder="••••••••"
              required
              size="md"
              :disabled="loading"
              :ui="{ rounded: 'rounded-lg' }"
            />
          </UFormGroup>

          <UButton
            type="submit"
            block
            color="emerald"
            class="text-xs font-semibold uppercase tracking-wider py-2.5 rounded-lg mt-2"
            :loading="loading"
          >
            Entrar na Conta
          </UButton>
        </form>
      </UCard>

      <!-- Footer navigation links -->
      <p class="text-center text-xs text-gray-400 select-none">
        Não tem uma conta? 
        <NuxtLink to="/register" class="text-emerald-500 hover:text-emerald-600 font-semibold underline">
          Cadastre-se gratuitamente
        </NuxtLink>
      </p>
    </div>
  </main>
</template>

<script setup lang="ts">
import { ref } from 'vue'

definePageMeta({
  layout: false
})

const email = ref('')
const password = ref('')
const error = ref('')
const success = ref('')
const loading = ref(false)

const { login } = useAuth()

const handleSubmit = async () => {
  error.value = ''
  success.value = ''
  loading.value = true

  const result = await login(email.value, password.value)
  if (result.success) {
    success.value = 'Acesso concedido! Carregando painel...'
    setTimeout(() => {
      navigateTo('/dashboard')
    }, 1200)
  } else {
    error.value = result.message || 'Erro ao tentar acessar. Verifique seus dados.'
    loading.value = false
  }
}
</script>

// nextjs/app/login/page.tsx
"use client";

import React, { useState, useEffect, Suspense } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import Link from "next/link";
import { signIn } from "next-auth/react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card } from "@/components/ui/card";
import { toast } from "sonner";

function LoginForm() {
  const router = useRouter();
  const searchParams = useSearchParams();

  // Form state
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  // UI state
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (searchParams.get("registered") === "true") {
      toast.success("Cadastro realizado!", {
        description: "Utilize suas credenciais para acessar a plataforma.",
      });
    }
  }, [searchParams]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);

    try {
      const result = await signIn("credentials", {
        email,
        password,
        redirect: false,
      });

      if (result?.error) {
        setLoading(false);
        toast.error("Falha na Autenticação", {
          description: "E-mail ou senha incorretos, ou conta desativada.",
        });
      } else {
        router.push("/dashboard");
        router.refresh();
      }
    } catch (err) {
      setLoading(false);
      toast.error("Erro de Conexão", {
        description: "Erro de conexão ao tentar fazer login.",
      });
    }
  };

  return (
    <form onSubmit={handleSubmit} className="grid gap-4 pt-2">
      {/* Email */}
      <div className="grid gap-1.5 text-left">
        <Label htmlFor="email" className="text-slate-300 text-xs font-semibold uppercase tracking-wider">Endereço de E-mail</Label>
        <Input
          id="email"
          type="email"
          required
          placeholder="nome@empresa.com"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          className="w-full bg-slate-950/60 border-slate-800 rounded-xl px-4 py-6 text-white placeholder-slate-500 focus-visible:border-emerald-500 focus-visible:ring-emerald-500/20 text-sm transition-all"
        />
      </div>

      {/* Password */}
      <div className="grid gap-1.5 text-left">
        <Label htmlFor="password" className="text-slate-300 text-xs font-semibold uppercase tracking-wider">Senha</Label>
        <Input
          id="password"
          type="password"
          required
          placeholder="••••••••"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
          className="w-full bg-slate-950/60 border-slate-800 rounded-xl px-4 py-6 text-white placeholder-slate-500 focus-visible:border-emerald-500 focus-visible:ring-emerald-500/20 text-sm transition-all"
        />
      </div>

      {/* Submit Button */}
      <Button
        type="submit"
        disabled={loading}
        className="w-full mt-2 bg-gradient-to-r from-emerald-600 to-green-600 hover:from-emerald-500 hover:to-green-500 text-white font-semibold rounded-xl py-6 transition-all flex items-center justify-center gap-2 text-sm focus-visible:ring-emerald-500/20 shadow-lg shadow-emerald-500/10 cursor-pointer active:scale-[0.98]"
      >
        {loading ? (
          <>
            <svg className="animate-spin h-5 w-5 text-white" fill="none" viewBox="0 0 24 24">
              <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
              <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
            </svg>
            <span>Autenticando...</span>
          </>
        ) : (
          <span>Entrar no sistema</span>
        )}
      </Button>
    </form>
  );
}

export default function LoginPage() {
  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 font-sans flex items-center justify-center p-4 relative overflow-hidden">
      {/* Background Glows */}
      <div className="absolute top-1/4 left-1/4 w-[500px] h-[500px] bg-emerald-500/10 rounded-full blur-3xl animate-pulse pointer-events-none" />
      <div className="absolute bottom-1/4 right-1/4 w-[500px] h-[500px] bg-green-500/10 rounded-full blur-3xl pointer-events-none" />

      <div className="w-full max-w-md space-y-6 relative z-10">
        {/* Logo and title */}
        <div className="text-center space-y-2 select-none">
          <div className="inline-flex w-12 h-12 rounded-2xl bg-gradient-to-tr from-emerald-500 to-green-600 text-white items-center justify-center font-bold text-lg shadow-lg shadow-emerald-500/20 mb-2">
            MF
          </div>
          <h1 className="text-2xl font-bold tracking-tight text-white">MEI Finance</h1>
          <p className="text-sm text-slate-400">
            Gerencie suas finanças PJ e PF no mesmo lugar.
          </p>
        </div>

        <Card className="bg-slate-900/35 backdrop-blur-md border border-slate-800/80 rounded-2xl p-6 sm:p-8 shadow-2xl shadow-emerald-500/2 hover:border-emerald-500/20 transition-all duration-300">
          <div className="space-y-4">
            <div className="space-y-1.5 text-center">
              <h2 className="text-2xl font-bold tracking-tight text-white">
                Acesse sua Conta
              </h2>
              <p className="text-slate-400 text-xs">
                Não tem uma conta de contador?{" "}
                <Link
                  href="/register"
                  className="font-semibold text-emerald-400 hover:text-emerald-300 transition-colors hover:underline"
                >
                  Cadastre-se grátis
                </Link>
              </p>
            </div>

            <Suspense fallback={<div className="text-slate-400 text-center text-sm py-4">Carregando formulário...</div>}>
              <LoginForm />
            </Suspense>
          </div>
        </Card>

        <p className="text-center text-xs text-slate-500 select-none">
          &copy; {new Date().getFullYear()} MEI Finance. Todos os direitos reservados.
        </p>
      </div>
    </div>
  );
}
